const misspells = [
  "Abi-Dalzim's Torrid Wilting",
  "Abi-Dalzim's Horrid Wiling",
  "Abi-Dalzim's Horrid Jilting",
  "Abi-Dalzim's Horrid Lilting",
  "Abi-Dalzim's Horrid Silting",
  "Abi-Dalzim's Horrid Tilting",
  "Abi-Dalzim's Horrid Witting",
  "Abi-Dalzim's Horrid Willing",
  "Adsorb Elements",
  "Acrid Splash",
  "Aid Splash",
  "Amid Splash",
  "Arid Splash",
  "Avid Splash",
  "Aced Splash",
  "Acid Splashy",
  "Acid Slash",
  "Aganazzar's Scorched",
  "Aganazzar's Scorches",
  "Acid",
  "Aide",
  "Laid",
  "Maid",
  "Amid",
  "Paid",
  "Raid",
  "Arid",
  "Said",
  "Avid",
  "Id",
  "Bid",
  "Did",
  "Hid",
  "Kid",
  "Lid",
  "Mid",
  "Rid",
  "Add",
  "And",
  "Ail",
  "Aim",
  "Air",
  "Falter Self",
  "Halter Self",
  "After Self",
  "Aster Self",
  "Alder Self",
  "Altar Self",
  "Later Self",
  "Alter Shelf",
  "Alter Elf",
  "Alter Serf",
  "Alter Sell",
  "Animal Shapers",
  "Animal Stapes",
  "Animal Shades",
  "Animal Shakes",
  "Animal Shames",
  "Animal Shares",
  "Animal Shaves",
  "Animal Shaped",
  "Animal Shaper",
  "Animate Dread",
  "Animate Dad",
  "Animate Bead",
  "Animate Head",
  "Animate Lead",
  "Animate Mead",
  "Animate Read",
  "Animate Dyad",
  "Animate Deed",
  "Animate Deaf",
  "Animate Deal",
  "Animate Dean",
  "Animate Dear",
  "Antilife Hell",
  "Antilife Sell",
  "Antilife Smell",
  "Antilife Spell",
  "Antilife Swell",
  "Antilife Shall",
  "Antilife Shelf",
  "Antimagic Afield",
  "Antimagic Wield",
  "Antimagic Yield",
  "Antimagic Fiend",
  "Antimagic Filed",
  "Arcade Eye",
  "Arcana Eye",
  "Arcane Ye",
  "Arcane Aye",
  "Arcane Bye",
  "Arcane Dye",
  "Arcane Lye",
  "Arcane Rye",
  "Arcane Eke",
  "Arcane Ere",
  "Arcane Eve",
  "Arcane Ewe",
  "Arcade Gate",
  "Arcana Gate",
  "Arcane Grate",
  "Arcane Ate",
  "Arcane Bate",
  "Arcane Date",
  "Arcane Fate",
  "Arcane Hate",
  "Arcane Late",
  "Arcane Mate",
  "Arcane Pate",
  "Arcane Rate",
  "Arcane Gage",
  "Arcane Gale",
  "Arcane Game",
  "Arcane Gape",
  "Arcane Gave",
  "Arcane Gaze",
  "Arcade Lock",
  "Arcana Lock",
  "Arcane Block",
  "Arcane Clock",
  "Arcane Flock",
  "Arcane Cock",
  "Arcane Dock",
  "Arcane Hock",
  "Arcane Jock",
  "Arcane Mock",
  "Arcane Pock",
  "Arcane Rock",
  "Arcane Sock",
  "Arcane Lack",
  "Arcane Lick",
  "Arcane Luck",
  "Arcane Look",
  "Arcane Loch",
  "Arcane Loci",
  "Arcane Loco",
  "Armour of Agathys",
  "Arbor of Agathys",
  "Armor Oaf Agathys",
  "Armor Off Agathys",
  "Armor Off Agathys",
  "Armor If Agathys",
  "Armor Oh Agathys",
  "Armor On Agathys",
  "Armor Or Agathys",
  "Armor Ow Agathys",
  "Armor Ox Agathys",
  "Farms of Hadar",
  "Harms of Hadar",
  "Warms of Hadar",
  "Aims of Hadar",
  "Alms of Hadar",
  "Arcs of Hadar",
  "Arks of Hadar",
  "Arts of Hadar",
  "Army of Hadar",
  "Rams of Hadar",
  "Arms Oaf Hadar",
  "Arms Off Hadar",
  "Arms Off Hadar",
  "Arms If Hadar",
  "Arms Oh Hadar",
  "Arms On Hadar",
  "Arms Or Hadar",
  "Arms Ow Hadar",
  "Arms Ox Hadar",
  "Arms of Radar",
  "Ashardalon's Astride",
  "Ashardalon's Strider",
  "Ashardalon's Strode",
  "Ashardalon's Strife",
  "Ashardalon's Strike",
  "Ashardalon's Stripe",
  "Ashardalon's Strive",
  "Austral Projection",
  "Antral Projection",
  "Astray Projection",
  "Astral Protection",
  "Augur",
  "Augurs",
  "Aural of Life",
  "Aura Oaf Life",
  "Aura Off Life",
  "Aura Off Life",
  "Aura If Life",
  "Aura Oh Life",
  "Aura On Life",
  "Aura Or Life",
  "Aura Ow Life",
  "Aura Ox Life",
  "Aura of Lie",
  "Aura of Fife",
  "Aura of Rife",
  "Aura of Wife",
  "Aura of Lice",
  "Aura of Like",
  "Aura of Lime",
  "Aura of Line",
  "Aura of Lire",
  "Aura of Live",
  "Aura of Lift",
  "Aural of Purity",
  "Aura Oaf Purity",
  "Aura Off Purity",
  "Aura Off Purity",
  "Aura If Purity",
  "Aura Oh Purity",
  "Aura On Purity",
  "Aura Or Purity",
  "Aura Ow Purity",
  "Aura Ox Purity",
  "Aura of Parity",
  "Aura of Purify",
  "Aural of Vitality",
  "Aura Oaf Vitality",
  "Aura Off Vitality",
  "Aura Off Vitality",
  "Aura If Vitality",
  "Aura Oh Vitality",
  "Aura On Vitality",
  "Aura Or Vitality",
  "Aura Ow Vitality",
  "Aura Ox Vitality",
  "Waken",
  "Awake",
  "Awoken",
  "Awakes",
  "Ban",
  "Cane",
  "Dane",
  "Lane",
  "Mane",
  "Pane",
  "Sane",
  "Vane",
  "Wane",
  "Bone",
  "Babe",
  "Bade",
  "Bake",
  "Bale",
  "Bare",
  "Base",
  "Bate",
  "Band",
  "Bang",
  "Bank",
  "Bans",
  "Vanishing Smite",
  "Banishing Semite",
  "Banishing Mite",
  "Banishing Site",
  "Banishing Spite",
  "Banishing Suite",
  "Banishing Smote",
  "Banishing Smile",
  "Banishing Smith",
  "Bacon of Hope",
  "Deacon of Hope",
  "Beacon Oaf Hope",
  "Beacon Off Hope",
  "Beacon Off Hope",
  "Beacon If Hope",
  "Beacon Oh Hope",
  "Beacon On Hope",
  "Beacon Or Hope",
  "Beacon Ow Hope",
  "Beacon Ox Hope",
  "Beacon of Hoe",
  "Beacon of Hop",
  "Beacon of Cope",
  "Beacon of Dope",
  "Beacon of Lope",
  "Beacon of Mope",
  "Beacon of Pope",
  "Beacon of Rope",
  "Beacon of Hype",
  "Beacon of Hole",
  "Beacon of Home",
  "Beacon of Hone",
  "Beacon of Hose",
  "Beacon of Hove",
  "Beacon of Hops",
  "Breast Bond",
  "East Bond",
  "Best Bond",
  "Beat Bond",
  "Feast Bond",
  "Least Bond",
  "Yeast Bond",
  "Blast Bond",
  "Boast Bond",
  "Beats Bond",
  "Beast Boned",
  "Beast Blond",
  "Beast Bound",
  "Beast Fond",
  "Beast Pond",
  "Beast Band",
  "Beast Bend",
  "Beast Bind",
  "Beast Bold",
  "Beast Bone",
  "Beast Bong",
  "Beast Bonn",
  "Beast Bony",
  "Breast Sense",
  "East Sense",
  "Best Sense",
  "Beat Sense",
  "Feast Sense",
  "Least Sense",
  "Yeast Sense",
  "Blast Sense",
  "Boast Sense",
  "Beats Sense",
  "Beast Dense",
  "Beast Tense",
  "Bestow Course",
  "Bestow Cure",
  "Bestow Curs",
  "Bestow Nurse",
  "Bestow Purse",
  "Bestow Corse",
  "Bestow Curie",
  "Bestow Curve",
  "Bestow Cures",
  "Bigby's Handy",
  "Bigby's And",
  "Bigby's Had",
  "Bigby's Band",
  "Bigby's Land",
  "Bigby's Rand",
  "Bigby's Sand",
  "Bigby's Wand",
  "Bigby's Hind",
  "Bigby's Hard",
  "Bigby's Hang",
  "Lade Barrier",
  "Bade Barrier",
  "Glade Barrier",
  "Blame Barrier",
  "Blare Barrier",
  "Blase Barrier",
  "Blaze Barrier",
  "Blade Carrier",
  "Blade Farrier",
  "Blade Harrier",
  "Blade Tarrier",
  "Lade of Disaster",
  "Bade of Disaster",
  "Glade of Disaster",
  "Blame of Disaster",
  "Blare of Disaster",
  "Blase of Disaster",
  "Blaze of Disaster",
  "Blade Oaf Disaster",
  "Blade Off Disaster",
  "Blade Off Disaster",
  "Blade If Disaster",
  "Blade Oh Disaster",
  "Blade On Disaster",
  "Blade Or Disaster",
  "Blade Ow Disaster",
  "Blade Ox Disaster",
  "Lade Ward",
  "Bade Ward",
  "Glade Ward",
  "Blame Ward",
  "Blare Ward",
  "Blase Ward",
  "Blaze Ward",
  "Blade Award",
  "Blade Sward",
  "Blade Wad",
  "Blade War",
  "Blade Bard",
  "Blade Card",
  "Blade Hard",
  "Blade Lard",
  "Blade Yard",
  "Blade Word",
  "Blade Wand",
  "Blade Ware",
  "Blade Warm",
  "Blade Warn",
  "Blade Warp",
  "Blade Wars",
  "Blade Wart",
  "Blade Wary",
  "Less",
  "Bliss",
  "Light",
  "Alight",
  "Flight",
  "Plight",
  "Slight",
  "Bright",
  "Binding Smite",
  "Blending Smite",
  "Blinking Smite",
  "Blinding Semite",
  "Blinding Mite",
  "Blinding Site",
  "Blinding Spite",
  "Blinding Suite",
  "Blinding Smote",
  "Blinding Smile",
  "Blinding Smith",
  "Link",
  "Clink",
  "Slink",
  "Brink",
  "Blank",
  "Blind",
  "Blurb",
  "Bluer",
  "Blurt",
  "Lur",
  "Bur",
  "Slur",
  "Blue",
  "Ones of the Earth",
  "Cones of the Earth",
  "Hones of the Earth",
  "Sones of the Earth",
  "Tones of the Earth",
  "Zones of the Earth",
  "Bodes of the Earth",
  "Bores of the Earth",
  "Boxes of the Earth",
  "Bonds of the Earth",
  "Bongs of the Earth",
  "Bonus of the Earth",
  "Boned of the Earth",
  "Boney of the Earth",
  "Bones Oaf the Earth",
  "Bones Off the Earth",
  "Bones Off the Earth",
  "Bones If the Earth",
  "Bones Oh the Earth",
  "Bones On the Earth",
  "Bones Or the Earth",
  "Bones Ow the Earth",
  "Bones Ox the Earth",
  "Bones of Thee Earth",
  "Bones of Thee Earth",
  "Bones of Them Earth",
  "Bones of Then Earth",
  "Bones of They Earth",
  "Bones of He Earth",
  "Bones of She Earth",
  "Bones of Tee Earth",
  "Bones of Tie Earth",
  "Bones of Toe Earth",
  "Bones of Thy Earth",
  "Bones of the Dearth",
  "Bones of the Hearth",
  "Bones of the Earthy",
  "Blooming Blade",
  "Booing Blade",
  "Dooming Blade",
  "Looming Blade",
  "Zooming Blade",
  "Booking Blade",
  "Booting Blade",
  "Booming Lade",
  "Booming Bade",
  "Booming Glade",
  "Booming Blame",
  "Booming Blare",
  "Booming Blase",
  "Booming Blaze",
  "Banding Smite",
  "Braiding Smite",
  "Branding Semite",
  "Branding Mite",
  "Branding Site",
  "Branding Spite",
  "Branding Suite",
  "Branding Smote",
  "Branding Smile",
  "Branding Smith",
  "Turning Hands",
  "Burping Hands",
  "Burying Hands",
  "Burning Bands",
  "Burning Lands",
  "Burning Rands",
  "Burning Sands",
  "Burning Wands",
  "Burning Hangs",
  "Burning Handy",
  "All Lightning",
  "Ball Lightning",
  "Fall Lightning",
  "Gall Lightning",
  "Hall Lightning",
  "Mall Lightning",
  "Pall Lightning",
  "Tall Lightning",
  "Wall Lightning",
  "Cell Lightning",
  "Cull Lightning",
  "Calf Lightning",
  "Calm Lightning",
  "Call Lightening",
  "Call Lighting",
  "Cam Emotions",
  "Balm Emotions",
  "Palm Emotions",
  "Calf Emotions",
  "Call Emotions",
  "Clam Emotions",
  "Calm Motions",
  "Catnip",
  "Clause Fear",
  "Case Fear",
  "Pause Fear",
  "Cause Ear",
  "Cause Far",
  "Cause Bear",
  "Cause Dear",
  "Cause Gear",
  "Cause Hear",
  "Cause Near",
  "Cause Pear",
  "Cause Rear",
  "Cause Sear",
  "Cause Tear",
  "Cause Wear",
  "Cause Year",
  "Cause Feat",
  "Cain Lightning",
  "Chin Lightning",
  "Chair Lightning",
  "Chain Lightening",
  "Chain Lighting",
  "Chaps Bolt",
  "Chars Bolt",
  "Chats Bolt",
  "Chaos Colt",
  "Chaos Dolt",
  "Chaos Jolt",
  "Chaos Volt",
  "Chaos Belt",
  "Chaos Boat",
  "Chaos Boot",
  "Chaos Bout",
  "Chaos Bola",
  "Chaos Bold",
  "Chaos Bole",
  "Chaos Blot",
  "Harm Monster",
  "Char Monster",
  "Chasm Monster",
  "Chars Monster",
  "Chart Monster",
  "Chary Monster",
  "Charm Minster",
  "Charm Mobster",
  "Charm Moister",
  "Harm Person",
  "Char Person",
  "Chasm Person",
  "Chars Person",
  "Chart Person",
  "Chary Person",
  "Charm Persona",
  "Charm Parson",
  "Charm Perron",
  "Chilli Touch",
  "Chilly Touch",
  "Hill Touch",
  "Child Touch",
  "Chili Touch",
  "Chill Touche",
  "Chill Touchy",
  "Chill Ouch",
  "Chill Couch",
  "Chill Pouch",
  "Chill Vouch",
  "Chill Torch",
  "Chill Tough",
  "Achromatic Orb",
  "Chromatic Or",
  "Chromatic Ore",
  "Chromatic Rob",
  "Circlet of Death",
  "Circle Oaf Death",
  "Circle Off Death",
  "Circle Off Death",
  "Circle If Death",
  "Circle Oh Death",
  "Circle On Death",
  "Circle Or Death",
  "Circle Ow Death",
  "Circle Ox Death",
  "Circle of Dearth",
  "Circle of Heath",
  "Circle of Depth",
  "Circlet of Power",
  "Circle Oaf Power",
  "Circle Off Power",
  "Circle Off Power",
  "Circle If Power",
  "Circle Oh Power",
  "Circle On Power",
  "Circle Or Power",
  "Circle Ow Power",
  "Circle Ox Power",
  "Circle of Powder",
  "Circle of Bower",
  "Circle of Cower",
  "Circle of Lower",
  "Circle of Mower",
  "Circle of Rower",
  "Circle of Sower",
  "Circle of Tower",
  "Circle of Poker",
  "Circle of Poser",
  "Lone",
  "Cone",
  "Alone",
  "Crone",
  "Close",
  "Clove",
  "Cloudy of Daggers",
  "Loud of Daggers",
  "Clod of Daggers",
  "Aloud of Daggers",
  "Clout of Daggers",
  "Cloud Oaf Daggers",
  "Cloud Off Daggers",
  "Cloud Off Daggers",
  "Cloud If Daggers",
  "Cloud Oh Daggers",
  "Cloud On Daggers",
  "Cloud Or Daggers",
  "Cloud Ow Daggers",
  "Cloud Ox Daggers",
  "Cloud of Diggers",
  "Cloud of Dangers",
  "Colour Spray",
  "Colon Spray",
  "Color Pray",
  "Color Spay",
  "Color Spry",
  "Color Stray",
  "Color Sprat",
  "Commando",
  "Commend",
  "Commute",
  "Commute with Nature",
  "Commune Witch Nature",
  "Commune Width Nature",
  "Commune Wit Nature",
  "Commune Kith Nature",
  "Commune Pith Nature",
  "Commune Wish Nature",
  "Commune Wits Nature",
  "Commune with Mature",
  "Compelled Due",
  "Compelled Fuel",
  "Compelled Dual",
  "Compelled Dull",
  "Compelled Dues",
  "Compelled Duet",
  "Clone of Cold",
  "Crone of Cold",
  "Scone of Cold",
  "One of Cold",
  "Con of Cold",
  "Bone of Cold",
  "Done of Cold",
  "Gone of Cold",
  "Hone of Cold",
  "Lone of Cold",
  "None of Cold",
  "Tone of Cold",
  "Zone of Cold",
  "Cane of Cold",
  "Cine of Cold",
  "Code of Cold",
  "Coke of Cold",
  "Cole of Cold",
  "Come of Cold",
  "Cope of Cold",
  "Core of Cold",
  "Cove of Cold",
  "Conk of Cold",
  "Cons of Cold",
  "Cony of Cold",
  "Cone Oaf Cold",
  "Cone Off Cold",
  "Cone Off Cold",
  "Cone If Cold",
  "Cone Oh Cold",
  "Cone On Cold",
  "Cone Or Cold",
  "Cone Ow Cold",
  "Cone Ox Cold",
  "Cone of Scold",
  "Cone of Could",
  "Cone of Old",
  "Cone of Cod",
  "Cone of Col",
  "Cone of Bold",
  "Cone of Fold",
  "Cone of Gold",
  "Cone of Hold",
  "Cone of Mold",
  "Cone of Sold",
  "Cone of Told",
  "Cone of Wold",
  "Cone of Cord",
  "Cone of Cola",
  "Cone of Cole",
  "Cone of Cols",
  "Cone of Colt",
  "Cone of Clod",
  "Contusion",
  "Conjurer Animals",
  "Conjury Animals",
  "Conjurer Barrage",
  "Conjury Barrage",
  "Conjurer Celestial",
  "Conjury Celestial",
  "Conjurer Elemental",
  "Conjury Elemental",
  "Conjurer Fey",
  "Conjury Fey",
  "Conjure Hey",
  "Conjure Key",
  "Conjure Fly",
  "Conjure Fry",
  "Conjure Fed",
  "Conjure Fee",
  "Conjure Fen",
  "Conjure Few",
  "Conjure Fez",
  "Conjurer Minor Elementals",
  "Conjury Minor Elementals",
  "Conjure Manor Elementals",
  "Conjure Miner Elementals",
  "Conjurer Volley",
  "Conjury Volley",
  "Conjure Valley",
  "Conjurer Woodland Beings",
  "Conjury Woodland Beings",
  "Conjure Woodland Brings",
  "Contract Other Plane",
  "Contact Bother Plane",
  "Contact Mother Plane",
  "Contact Ether Plane",
  "Contact Otter Plane",
  "Contact Other Planet",
  "Contact Other Lane",
  "Contact Other Pane",
  "Contact Other Plan",
  "Contact Other Place",
  "Contact Other Plate",
  "Contact Other Plank",
  "Contact Other Plans",
  "Contact Other Plant",
  "Continua Flame",
  "Continual Aflame",
  "Continual Lame",
  "Continual Fame",
  "Continual Blame",
  "Continual Frame",
  "Continual Flake",
  "Continual Flare",
  "Control Blames",
  "Control Frames",
  "Control Flumes",
  "Control Flakes",
  "Control Flares",
  "Control Flamed",
  "Control Waiter",
  "Control Waster",
  "Control Watery",
  "Control Cater",
  "Control Eater",
  "Control Hater",
  "Control Later",
  "Control Mater",
  "Control Pater",
  "Control Rater",
  "Control Wader",
  "Control Wafer",
  "Control Wager",
  "Control Waver",
  "Control Wether",
  "Control Feather",
  "Control Heather",
  "Control Leather",
  "Control Wins",
  "Control Binds",
  "Control Finds",
  "Control Kinds",
  "Control Minds",
  "Control Rinds",
  "Control Wands",
  "Control Wends",
  "Control Wilds",
  "Control Wines",
  "Control Wings",
  "Control Winks",
  "Control Windy",
  "Cordon Oaf Arrows",
  "Cordon Off Arrows",
  "Cordon Off Arrows",
  "Cordon If Arrows",
  "Cordon Oh Arrows",
  "Cordon On Arrows",
  "Cordon Or Arrows",
  "Cordon Ow Arrows",
  "Cordon Ox Arrows",
  "Cordon of Barrows",
  "Cordon of Harrows",
  "Cordon of Marrows",
  "Cordon of Narrows",
  "Cremate Bonfire",
  "Crate Bonfire",
  "Crete Bonfire",
  "Crease Bonfire",
  "Cremate Food and Water",
  "Crate Food and Water",
  "Crete Food and Water",
  "Crease Food and Water",
  "Create Flood and Water",
  "Create Good and Water",
  "Create Hood and Water",
  "Create Mood and Water",
  "Create Wood and Water",
  "Create Fold and Water",
  "Create Fond and Water",
  "Create Ford and Water",
  "Create Fool and Water",
  "Create Foot and Water",
  "Create Food Band Water",
  "Create Food Hand Water",
  "Create Food Land Water",
  "Create Food Rand Water",
  "Create Food Sand Water",
  "Create Food Wand Water",
  "Create Food An Water",
  "Create Food End Water",
  "Create Food Add Water",
  "Create Food Aid Water",
  "Create Food Ant Water",
  "Create Food Any Water",
  "Create Food and Waiter",
  "Create Food and Waster",
  "Create Food and Watery",
  "Create Food and Cater",
  "Create Food and Eater",
  "Create Food and Hater",
  "Create Food and Later",
  "Create Food and Mater",
  "Create Food and Pater",
  "Create Food and Rater",
  "Create Food and Wader",
  "Create Food and Wafer",
  "Create Food and Wager",
  "Create Food and Waver",
  "Cremate Homunculus",
  "Crate Homunculus",
  "Crete Homunculus",
  "Crease Homunculus",
  "Cremate Magen",
  "Crate Magen",
  "Crete Magen",
  "Crease Magen",
  "Cremate or Destroy Water",
  "Crate or Destroy Water",
  "Crete or Destroy Water",
  "Crease or Destroy Water",
  "Create Oar Destroy Water",
  "Create Orb Destroy Water",
  "Create Ore Destroy Water",
  "Create For Destroy Water",
  "Create Nor Destroy Water",
  "Create Our Destroy Water",
  "Create Dr Destroy Water",
  "Create Mr Destroy Water",
  "Create Of Destroy Water",
  "Create Oh Destroy Water",
  "Create On Destroy Water",
  "Create Ow Destroy Water",
  "Create Ox Destroy Water",
  "Create or Destroy Waiter",
  "Create or Destroy Waster",
  "Create or Destroy Watery",
  "Create or Destroy Cater",
  "Create or Destroy Eater",
  "Create or Destroy Hater",
  "Create or Destroy Later",
  "Create or Destroy Mater",
  "Create or Destroy Pater",
  "Create or Destroy Rater",
  "Create or Destroy Wader",
  "Create or Destroy Wafer",
  "Create or Destroy Wager",
  "Create or Destroy Waver",
  "Cremate Undead",
  "Crate Undead",
  "Crete Undead",
  "Crease Undead",
  "Create Unread",
  "Cremation",
  "Crow of Madness",
  "Brown of Madness",
  "Drown of Madness",
  "Frown of Madness",
  "Grown of Madness",
  "Clown of Madness",
  "Croon of Madness",
  "Crowd of Madness",
  "Crows of Madness",
  "Crown Oaf Madness",
  "Crown Off Madness",
  "Crown Off Madness",
  "Crown If Madness",
  "Crown Oh Madness",
  "Crown On Madness",
  "Crown Or Madness",
  "Crown Ow Madness",
  "Crown Ox Madness",
  "Crown of Badness",
  "Crown of Sadness",
  "Crow of Stars",
  "Brown of Stars",
  "Drown of Stars",
  "Frown of Stars",
  "Grown of Stars",
  "Clown of Stars",
  "Croon of Stars",
  "Crowd of Stars",
  "Crows of Stars",
  "Crown Oaf Stars",
  "Crown Off Stars",
  "Crown Off Stars",
  "Crown If Stars",
  "Crown Oh Stars",
  "Crown On Stars",
  "Crown Or Stars",
  "Crown Ow Stars",
  "Crown Ox Stars",
  "Crown of Stares",
  "Crown of Stairs",
  "Crown of Starts",
  "Crown of Tars",
  "Crown of Scars",
  "Crown of Sears",
  "Crown of Soars",
  "Crown of Spars",
  "Crown of Stirs",
  "Crown of Stabs",
  "Crown of Stags",
  "Crown of Stays",
  "Crown of Stare",
  "Crown of Stark",
  "Crown of Start",
  "Crusader's Mangle",
  "Crusader's Mantel",
  "Curie Wounds",
  "Curer Wounds",
  "Curse Wounds",
  "Curve Wounds",
  "Cue Wounds",
  "Cur Wounds",
  "Lure Wounds",
  "Pure Wounds",
  "Sure Wounds",
  "Care Wounds",
  "Core Wounds",
  "Cube Wounds",
  "Cute Wounds",
  "Curb Wounds",
  "Curd Wounds",
  "Curl Wounds",
  "Curs Wounds",
  "Curt Wounds",
  "Cure Bounds",
  "Cure Founds",
  "Cure Hounds",
  "Cure Mounds",
  "Cure Pounds",
  "Cure Rounds",
  "Cure Sounds",
  "Lancing Lights",
  "Dancing Alights",
  "Dancing Blights",
  "Dancing Flights",
  "Dancing Plights",
  "Dancing Slights",
  "Dancing Eights",
  "Dancing Fights",
  "Dancing Mights",
  "Dancing Nights",
  "Dancing Rights",
  "Dancing Sights",
  "Dancing Tights",
  "Dane Macabre",
  "Manse Macabre",
  "Dense Macabre",
  "Dance Macabre",
  "Dante Macabre",
  "Danes Macabre",
  "Ark Star",
  "Bark Star",
  "Hark Star",
  "Lark Star",
  "Mark Star",
  "Park Star",
  "Dank Star",
  "Dare Star",
  "Darn Star",
  "Dart Star",
  "Dark Stare",
  "Dark Sitar",
  "Dark Stair",
  "Dark Stark",
  "Dark Start",
  "Dark Tar",
  "Dark Scar",
  "Dark Sear",
  "Dark Soar",
  "Dark Spar",
  "Dark Stir",
  "Dark Stab",
  "Dark Stag",
  "Dark Stay",
  "Drawn",
  "Awn",
  "Dan",
  "Fawn",
  "Lawn",
  "Pawn",
  "Sawn",
  "Yawn",
  "Down",
  "Damn",
  "Darn",
  "Dearth Ward",
  "Heath Ward",
  "Depth Ward",
  "Death Award",
  "Death Sward",
  "Death Wad",
  "Death War",
  "Death Bard",
  "Death Card",
  "Death Hard",
  "Death Lard",
  "Death Yard",
  "Death Word",
  "Death Wand",
  "Death Ware",
  "Death Warm",
  "Death Warn",
  "Death Warp",
  "Death Wars",
  "Death Wart",
  "Death Wary",
  "Belayed Blast Fireball",
  "Relayed Blast Fireball",
  "Decayed Blast Fireball",
  "Delayed Last Fireball",
  "Delayed Blat Fireball",
  "Delayed Beast Fireball",
  "Delayed Boast Fireball",
  "Delayed Blase Fireball",
  "Destructive Weave",
  "Destructive Waive",
  "Destructive Waver",
  "Destructive Ave",
  "Destructive Cave",
  "Destructive Gave",
  "Destructive Have",
  "Destructive Nave",
  "Destructive Pave",
  "Destructive Rave",
  "Destructive Save",
  "Destructive Wove",
  "Destructive Wade",
  "Destructive Wage",
  "Destructive Wake",
  "Destructive Wane",
  "Destructive Ware",
  "Destructive Wavy",
  "Defect Evil and Good",
  "Deject Evil and Good",
  "Detent Evil and Good",
  "Detest Evil and Good",
  "Detect Devil and Good",
  "Detect Veil and Good",
  "Detect Evil Band Good",
  "Detect Evil Hand Good",
  "Detect Evil Land Good",
  "Detect Evil Rand Good",
  "Detect Evil Sand Good",
  "Detect Evil Wand Good",
  "Detect Evil An Good",
  "Detect Evil End Good",
  "Detect Evil Add Good",
  "Detect Evil Aid Good",
  "Detect Evil Ant Good",
  "Detect Evil Any Good",
  "Detect Evil and Goody",
  "Detect Evil and God",
  "Detect Evil and God",
  "Detect Evil and Goo",
  "Detect Evil and Food",
  "Detect Evil and Hood",
  "Detect Evil and Mood",
  "Detect Evil and Wood",
  "Detect Evil and Goad",
  "Detect Evil and Gold",
  "Detect Evil and Goof",
  "Detect Evil and Goon",
  "Defect Magic",
  "Deject Magic",
  "Detent Magic",
  "Detest Magic",
  "Detect Magi",
  "Detect Manic",
  "Defect Poison and Disease",
  "Deject Poison and Disease",
  "Detent Poison and Disease",
  "Detest Poison and Disease",
  "Detect Prison and Disease",
  "Detect Poison Band Disease",
  "Detect Poison Hand Disease",
  "Detect Poison Land Disease",
  "Detect Poison Rand Disease",
  "Detect Poison Sand Disease",
  "Detect Poison Wand Disease",
  "Detect Poison An Disease",
  "Detect Poison End Disease",
  "Detect Poison Add Disease",
  "Detect Poison Aid Disease",
  "Detect Poison Ant Disease",
  "Detect Poison Any Disease",
  "Defect Thoughts",
  "Deject Thoughts",
  "Detent Thoughts",
  "Detest Thoughts",
  "Dimension Donor",
  "Dimension Dor",
  "Dimension Dor",
  "Dimension Boor",
  "Dimension Moor",
  "Dimension Poor",
  "Dimension Doer",
  "Dimension Dour",
  "Dimension Doom",
  "Disguise Shelf",
  "Disguise Elf",
  "Disguise Serf",
  "Disguise Sell",
  "Dispel Devil and Good",
  "Dispel Veil and Good",
  "Dispel Evil Band Good",
  "Dispel Evil Hand Good",
  "Dispel Evil Land Good",
  "Dispel Evil Rand Good",
  "Dispel Evil Sand Good",
  "Dispel Evil Wand Good",
  "Dispel Evil An Good",
  "Dispel Evil End Good",
  "Dispel Evil Add Good",
  "Dispel Evil Aid Good",
  "Dispel Evil Ant Good",
  "Dispel Evil Any Good",
  "Dispel Evil and Goody",
  "Dispel Evil and God",
  "Dispel Evil and God",
  "Dispel Evil and Goo",
  "Dispel Evil and Food",
  "Dispel Evil and Hood",
  "Dispel Evil and Mood",
  "Dispel Evil and Wood",
  "Dispel Evil and Goad",
  "Dispel Evil and Gold",
  "Dispel Evil and Goof",
  "Dispel Evil and Goon",
  "Dispel Magi",
  "Dispel Manic",
  "Dissonant Whimpers",
  "Dissonant Whiskers",
  "Distort Valuer",
  "Distort Vale",
  "Distort Vague",
  "Distort Valve",
  "Diviner Favor",
  "Divide Favor",
  "Diving Favor",
  "Divine Favour",
  "Diviner Word",
  "Divide Word",
  "Diving Word",
  "Divine World",
  "Divine Sword",
  "Divine Wordy",
  "Divine Cord",
  "Divine Ford",
  "Divine Lord",
  "Divine Ward",
  "Divine Woad",
  "Divine Wold",
  "Divine Wood",
  "Divine Wore",
  "Divine Work",
  "Divine Worm",
  "Divine Worn",
  "Nominate Beast",
  "Dominate Breast",
  "Dominate East",
  "Dominate Best",
  "Dominate Beat",
  "Dominate Feast",
  "Dominate Least",
  "Dominate Yeast",
  "Dominate Blast",
  "Dominate Boast",
  "Dominate Beats",
  "Nominate Monster",
  "Dominate Minster",
  "Dominate Mobster",
  "Dominate Moister",
  "Nominate Person",
  "Dominate Persona",
  "Dominate Parson",
  "Dominate Perron",
  "Dragon's Breadth",
  "Dragon's Breathe",
  "Dragon's Breathy",
  "Dragon's Wreath",
  "Dragon's Breach",
  "Dreamt",
  "Dreamy",
  "Ream",
  "Dram",
  "Bream",
  "Cream",
  "Dread",
  "Drear",
  "Dreamt of the Blue Veil",
  "Dreamy of the Blue Veil",
  "Ream of the Blue Veil",
  "Dram of the Blue Veil",
  "Bream of the Blue Veil",
  "Cream of the Blue Veil",
  "Dread of the Blue Veil",
  "Drear of the Blue Veil",
  "Dream Oaf the Blue Veil",
  "Dream Off the Blue Veil",
  "Dream Off the Blue Veil",
  "Dream If the Blue Veil",
  "Dream Oh the Blue Veil",
  "Dream On the Blue Veil",
  "Dream Or the Blue Veil",
  "Dream Ow the Blue Veil",
  "Dream Ox the Blue Veil",
  "Dream of Thee Blue Veil",
  "Dream of Thee Blue Veil",
  "Dream of Them Blue Veil",
  "Dream of Then Blue Veil",
  "Dream of They Blue Veil",
  "Dream of He Blue Veil",
  "Dream of She Blue Veil",
  "Dream of Tee Blue Veil",
  "Dream of Tie Blue Veil",
  "Dream of Toe Blue Veil",
  "Dream of Thy Blue Veil",
  "Dream of the Bluer Veil",
  "Dream of the Clue Veil",
  "Dream of the Flue Veil",
  "Dream of the Glue Veil",
  "Dream of the Blur Veil",
  "Dream of the Blue Veal",
  "Dream of the Blue Vein",
  "Dream of the Blue Evil",
  "Druid Grovel",
  "Druid Groove",
  "Druid Groove",
  "Druid Rove",
  "Druid Drove",
  "Druid Prove",
  "Druid Trove",
  "Druid Glove",
  "Druid Grave",
  "Druid Grope",
  "Dusty Devil",
  "Bust Devil",
  "Gust Devil",
  "Just Devil",
  "Lust Devil",
  "Must Devil",
  "Oust Devil",
  "Rust Devil",
  "Duct Devil",
  "Duet Devil",
  "Dusk Devil",
  "Dust Evil",
  "Dearth Tremor",
  "Hearth Tremor",
  "Earthy Tremor",
  "Eldritch Last",
  "Eldritch Blat",
  "Eldritch Beast",
  "Eldritch Boast",
  "Eldritch Blase",
  "Elemental Ban",
  "Elemental Cane",
  "Elemental Dane",
  "Elemental Lane",
  "Elemental Mane",
  "Elemental Pane",
  "Elemental Sane",
  "Elemental Vane",
  "Elemental Wane",
  "Elemental Bone",
  "Elemental Babe",
  "Elemental Bade",
  "Elemental Bake",
  "Elemental Bale",
  "Elemental Bare",
  "Elemental Base",
  "Elemental Bate",
  "Elemental Band",
  "Elemental Bang",
  "Elemental Bank",
  "Elemental Bans",
  "Encoder Thoughts",
  "Encore Thoughts",
  "Enemies Bound",
  "Enemies Around",
  "Enhancer Ability",
  "Enhance Agility",
  "Ensnaring Striker",
  "Ensnaring Stroke",
  "Ensnaring Stride",
  "Ensnaring Strife",
  "Ensnaring Stripe",
  "Ensnaring Strive",
  "Entangler",
  "Untangle",
  "Erupting Dearth",
  "Erupting Hearth",
  "Erupting Earthy",
  "Evard's Lack Tentacles",
  "Evard's Back Tentacles",
  "Evard's Alack Tentacles",
  "Evard's Flack Tentacles",
  "Evard's Slack Tentacles",
  "Evard's Block Tentacles",
  "Evard's Blank Tentacles",
  "Evard's Black Tentacled",
  "Expeditions Retreat",
  "Expeditious Retread",
  "Faerie Afire",
  "Faerie Fibre",
  "Faerie Firer",
  "Faerie Ire",
  "Faerie Fir",
  "Faerie Aire",
  "Faerie Dire",
  "Faerie Eire",
  "Faerie Hire",
  "Faerie Lire",
  "Faerie Mire",
  "Faerie Sire",
  "Faerie Tire",
  "Faerie Wire",
  "Faerie Fare",
  "Faerie Fore",
  "Faerie Fife",
  "Faerie File",
  "Faerie Fine",
  "Faerie Five",
  "Faerie Firm",
  "Faerie Firs",
  "Falser Life",
  "False Lie",
  "False Fife",
  "False Rife",
  "False Wife",
  "False Lice",
  "False Like",
  "False Lime",
  "False Line",
  "False Lire",
  "False Live",
  "False Lift",
  "Afar Step",
  "Fear Step",
  "Fare Step",
  "Fair Step",
  "Farm Step",
  "Bar Step",
  "Car Step",
  "Ear Step",
  "Jar Step",
  "Mar Step",
  "Oar Step",
  "Par Step",
  "Tar Step",
  "War Step",
  "Fir Step",
  "For Step",
  "Fur Step",
  "Fab Step",
  "Fad Step",
  "Fag Step",
  "Fan Step",
  "Fat Step",
  "Fax Step",
  "Far Steep",
  "Far Steep",
  "Far Stoep",
  "Far Seep",
  "Far Stop",
  "Far Stem",
  "Far Stet",
  "Far Stew",
  "Feast Friends",
  "Faust Friends",
  "Fat Friends",
  "Cast Friends",
  "East Friends",
  "Last Friends",
  "Mast Friends",
  "Oast Friends",
  "Past Friends",
  "Vast Friends",
  "Wast Friends",
  "Fest Friends",
  "Fist Friends",
  "Fact Friends",
  "Fats Friends",
  "Fast Fiends",
  "Ear",
  "Far",
  "Bear",
  "Dear",
  "Gear",
  "Hear",
  "Near",
  "Pear",
  "Rear",
  "Sear",
  "Tear",
  "Wear",
  "Year",
  "Feat",
  "Feathery Fall",
  "Father Fall",
  "Heather Fall",
  "Leather Fall",
  "Weather Fall",
  "Feather All",
  "Feather Ball",
  "Feather Call",
  "Feather Gall",
  "Feather Hall",
  "Feather Mall",
  "Feather Pall",
  "Feather Tall",
  "Feather Wall",
  "Feather Fell",
  "Feather Fill",
  "Feather Full",
  "Feather Fail",
  "Reign Death",
  "Feign Dearth",
  "Feign Heath",
  "Feign Depth",
  "Fiend Familiar",
  "Fined Familiar",
  "Fin Familiar",
  "Bind Familiar",
  "Hind Familiar",
  "Kind Familiar",
  "Mind Familiar",
  "Rind Familiar",
  "Wind Familiar",
  "Fend Familiar",
  "Fond Familiar",
  "Fund Familiar",
  "Fine Familiar",
  "Finn Familiar",
  "Fins Familiar",
  "Find Familial",
  "Fiend Greater Steed",
  "Fined Greater Steed",
  "Fin Greater Steed",
  "Bind Greater Steed",
  "Hind Greater Steed",
  "Kind Greater Steed",
  "Mind Greater Steed",
  "Rind Greater Steed",
  "Wind Greater Steed",
  "Fend Greater Steed",
  "Fond Greater Steed",
  "Fund Greater Steed",
  "Fine Greater Steed",
  "Finn Greater Steed",
  "Fins Greater Steed",
  "Find Grater Steed",
  "Find Greater Stewed",
  "Find Greater Teed",
  "Find Greater Seed",
  "Find Greater Speed",
  "Find Greater Stead",
  "Find Greater Steel",
  "Find Greater Steep",
  "Find Greater Steer",
  "Fiend Steed",
  "Fined Steed",
  "Fin Steed",
  "Bind Steed",
  "Hind Steed",
  "Kind Steed",
  "Mind Steed",
  "Rind Steed",
  "Wind Steed",
  "Fend Steed",
  "Fond Steed",
  "Fund Steed",
  "Fine Steed",
  "Finn Steed",
  "Fins Steed",
  "Find Stewed",
  "Find Teed",
  "Find Seed",
  "Find Speed",
  "Find Stead",
  "Find Steel",
  "Find Steep",
  "Find Steer",
  "Fiend the Path",
  "Fined the Path",
  "Fin the Path",
  "Bind the Path",
  "Hind the Path",
  "Kind the Path",
  "Mind the Path",
  "Rind the Path",
  "Wind the Path",
  "Fend the Path",
  "Fond the Path",
  "Fund the Path",
  "Fine the Path",
  "Finn the Path",
  "Fins the Path",
  "Find Thee Path",
  "Find Thee Path",
  "Find Them Path",
  "Find Then Path",
  "Find They Path",
  "Find He Path",
  "Find She Path",
  "Find Tee Path",
  "Find Tie Path",
  "Find Toe Path",
  "Find Thy Path",
  "Find the Patch",
  "Find the Pat",
  "Find the Bath",
  "Find the Lath",
  "Find the Math",
  "Find the Oath",
  "Find the Pith",
  "Find the Pate",
  "Find the Pats",
  "Fiend Traps",
  "Fined Traps",
  "Fin Traps",
  "Bind Traps",
  "Hind Traps",
  "Kind Traps",
  "Mind Traps",
  "Rind Traps",
  "Wind Traps",
  "Fend Traps",
  "Fond Traps",
  "Fund Traps",
  "Fine Traps",
  "Finn Traps",
  "Fins Traps",
  "Find Tramps",
  "Find Straps",
  "Find Raps",
  "Find Taps",
  "Find Wraps",
  "Find Trips",
  "Find Trams",
  "Find Trays",
  "Finer of Death",
  "Ginger of Death",
  "Linger of Death",
  "Ringer of Death",
  "Singer of Death",
  "Winger of Death",
  "Finder of Death",
  "Finger Oaf Death",
  "Finger Off Death",
  "Finger Off Death",
  "Finger If Death",
  "Finger Oh Death",
  "Finger On Death",
  "Finger Or Death",
  "Finger Ow Death",
  "Finger Ox Death",
  "Finger of Dearth",
  "Finger of Heath",
  "Finger of Depth",
  "Afire Bolt",
  "Fibre Bolt",
  "Firer Bolt",
  "Ire Bolt",
  "Fir Bolt",
  "Aire Bolt",
  "Dire Bolt",
  "Eire Bolt",
  "Hire Bolt",
  "Lire Bolt",
  "Mire Bolt",
  "Sire Bolt",
  "Tire Bolt",
  "Wire Bolt",
  "Fare Bolt",
  "Fore Bolt",
  "Fife Bolt",
  "File Bolt",
  "Fine Bolt",
  "Five Bolt",
  "Firm Bolt",
  "Firs Bolt",
  "Fire Colt",
  "Fire Dolt",
  "Fire Jolt",
  "Fire Volt",
  "Fire Belt",
  "Fire Boat",
  "Fire Boot",
  "Fire Bout",
  "Fire Bola",
  "Fire Bold",
  "Fire Bole",
  "Fire Blot",
  "Afire Shield",
  "Fibre Shield",
  "Firer Shield",
  "Ire Shield",
  "Fir Shield",
  "Aire Shield",
  "Dire Shield",
  "Eire Shield",
  "Hire Shield",
  "Lire Shield",
  "Mire Shield",
  "Sire Shield",
  "Tire Shield",
  "Wire Shield",
  "Fare Shield",
  "Fore Shield",
  "Fife Shield",
  "File Shield",
  "Fine Shield",
  "Five Shield",
  "Firm Shield",
  "Firs Shield",
  "Fire Shied",
  "Afire Storm",
  "Fibre Storm",
  "Firer Storm",
  "Ire Storm",
  "Fir Storm",
  "Aire Storm",
  "Dire Storm",
  "Eire Storm",
  "Hire Storm",
  "Lire Storm",
  "Mire Storm",
  "Sire Storm",
  "Tire Storm",
  "Wire Storm",
  "Fare Storm",
  "Fore Storm",
  "Fife Storm",
  "File Storm",
  "Fine Storm",
  "Five Storm",
  "Firm Storm",
  "Firs Storm",
  "Fire Stormy",
  "Fire Store",
  "Fire Stork",
  "Fire Story",
  "Fizban's Platinum Shied",
  "Aflame Arrows",
  "Lame Arrows",
  "Fame Arrows",
  "Blame Arrows",
  "Frame Arrows",
  "Flake Arrows",
  "Flare Arrows",
  "Flame Barrows",
  "Flame Harrows",
  "Flame Marrows",
  "Flame Narrows",
  "Aflame Blade",
  "Lame Blade",
  "Fame Blade",
  "Blame Blade",
  "Frame Blade",
  "Flake Blade",
  "Flare Blade",
  "Flame Lade",
  "Flame Bade",
  "Flame Glade",
  "Flame Blame",
  "Flame Blare",
  "Flame Blase",
  "Flame Blaze",
  "Aflame Strike",
  "Lame Strike",
  "Fame Strike",
  "Blame Strike",
  "Frame Strike",
  "Flake Strike",
  "Flare Strike",
  "Flame Striker",
  "Flame Stroke",
  "Flame Stride",
  "Flame Strife",
  "Flame Stripe",
  "Flame Strive",
  "Flamingo Sphere",
  "Blaming Sphere",
  "Foaming Sphere",
  "Framing Sphere",
  "Flaking Sphere",
  "Flaring Sphere",
  "Flaying Sphere",
  "Fleshy to Stone",
  "Fresh to Stone",
  "Flash to Stone",
  "Flush to Stone",
  "Flesh Toe Stone",
  "Flesh Tog Stone",
  "Flesh Ton Stone",
  "Flesh Too Stone",
  "Flesh Too Stone",
  "Flesh Top Stone",
  "Flesh Tot Stone",
  "Flesh Two Stone",
  "Flesh Tow Stone",
  "Flesh Toy Stone",
  "Flesh Do Stone",
  "Flesh Go Stone",
  "Flesh Ho Stone",
  "Flesh No Stone",
  "Flesh So Stone",
  "Flesh to Tone",
  "Flesh to Atone",
  "Flesh to Scone",
  "Flesh to Shone",
  "Flesh to Stoke",
  "Flesh to Stole",
  "Flesh to Store",
  "Flesh to Stove",
  "Flesh to Stony",
  "Lock of Familiars",
  "Block of Familiars",
  "Clock of Familiars",
  "Frock of Familiars",
  "Flack of Familiars",
  "Fleck of Familiars",
  "Flick of Familiars",
  "Flock Oaf Familiars",
  "Flock Off Familiars",
  "Flock Off Familiars",
  "Flock If Familiars",
  "Flock Oh Familiars",
  "Flock On Familiars",
  "Flock Or Familiars",
  "Flock Ow Familiars",
  "Flock Ox Familiars",
  "Flay",
  "Ply",
  "Sly",
  "Fry",
  "Flog Cloud",
  "Frog Cloud",
  "Fogy Cloud",
  "Bog Cloud",
  "Cog Cloud",
  "Dog Cloud",
  "Hog Cloud",
  "Jog Cloud",
  "Log Cloud",
  "Tog Cloud",
  "Fag Cloud",
  "Fig Cloud",
  "Fug Cloud",
  "Fob Cloud",
  "Foe Cloud",
  "Fop Cloud",
  "For Cloud",
  "Fox Cloud",
  "Fog Cloudy",
  "Fog Loud",
  "Fog Clod",
  "Fog Aloud",
  "Fog Clout",
  "Fortune's Favour",
  "Freedom Oaf Movement",
  "Freedom Off Movement",
  "Freedom Off Movement",
  "Freedom If Movement",
  "Freedom Oh Movement",
  "Freedom On Movement",
  "Freedom Or Movement",
  "Freedom Ow Movement",
  "Freedom Ox Movement",
  "Fiends",
  "Frosty Fingers",
  "Front Fingers",
  "Frost Gingers",
  "Frost Lingers",
  "Frost Ringers",
  "Frost Singers",
  "Frost Wingers",
  "Frost Finders",
  "Galder's Seedy Courier",
  "Galder's Speed Courier",
  "Galder's Speeds Courier",
  "Galder's Speedy Courtier",
  "Galder's Bower",
  "Galder's Cower",
  "Galder's Lower",
  "Galder's Mower",
  "Galder's Power",
  "Galder's Rower",
  "Galder's Sower",
  "Galder's Toner",
  "Galder's Towed",
  "Galder's Towel",
  "Gaseous Forum",
  "Gaseous For",
  "Gaseous Norm",
  "Gaseous Worm",
  "Gaseous Farm",
  "Gaseous Firm",
  "Gaseous Foam",
  "Gaseous Ford",
  "Gaseous Fore",
  "Gaseous Fork",
  "Gaseous Fort",
  "Gaseous From",
  "Grate",
  "Ate",
  "Bate",
  "Date",
  "Fate",
  "Hate",
  "Late",
  "Mate",
  "Pate",
  "Rate",
  "Gage",
  "Gale",
  "Game",
  "Gape",
  "Gave",
  "Gaze",
  "Gears",
  "Gas",
  "Peas",
  "Seas",
  "Teas",
  "Yeas",
  "Gels",
  "Gems",
  "Gets",
  "Gear",
  "Gentile Repose",
  "Gentler Repose",
  "Gently Repose",
  "Gentle Depose",
  "Grant Insect",
  "Giant Inspect",
  "Giant Inset",
  "Giant Infect",
  "Giant Inject",
  "Giant Insert",
  "Lift of Alacrity",
  "Rift of Alacrity",
  "Sift of Alacrity",
  "Gilt of Alacrity",
  "Girt of Alacrity",
  "Gist of Alacrity",
  "Gift Oaf Alacrity",
  "Gift Off Alacrity",
  "Gift Off Alacrity",
  "Gift If Alacrity",
  "Gift Oh Alacrity",
  "Gift On Alacrity",
  "Gift Or Alacrity",
  "Gift Ow Alacrity",
  "Gift Ox Alacrity",
  "Lift of Gab",
  "Rift of Gab",
  "Sift of Gab",
  "Gilt of Gab",
  "Girt of Gab",
  "Gist of Gab",
  "Gift Oaf Gab",
  "Gift Off Gab",
  "Gift Off Gab",
  "Gift If Gab",
  "Gift Oh Gab",
  "Gift On Gab",
  "Gift Or Gab",
  "Gift Ow Gab",
  "Gift Ox Gab",
  "Gift of Grab",
  "Gift of Garb",
  "Gift of Cab",
  "Gift of Dab",
  "Gift of Fab",
  "Gift of Jab",
  "Gift of Lab",
  "Gift of Nab",
  "Gift of Tab",
  "Gift of Gad",
  "Gift of Gag",
  "Gift of Gal",
  "Gift of Gap",
  "Gift of Gas",
  "Gift of Gay",
  "Lobe of Invulnerability",
  "Glob of Invulnerability",
  "Glebe of Invulnerability",
  "Glove of Invulnerability",
  "Globe Oaf Invulnerability",
  "Globe Off Invulnerability",
  "Globe Off Invulnerability",
  "Globe If Invulnerability",
  "Globe Oh Invulnerability",
  "Globe On Invulnerability",
  "Globe Or Invulnerability",
  "Globe Ow Invulnerability",
  "Globe Ox Invulnerability",
  "Glyph Oaf Warding",
  "Glyph Off Warding",
  "Glyph Off Warding",
  "Glyph If Warding",
  "Glyph Oh Warding",
  "Glyph On Warding",
  "Glyph Or Warding",
  "Glyph Ow Warding",
  "Glyph Ox Warding",
  "Glyph of Awarding",
  "Glyph of Wading",
  "Glyph of Waring",
  "Glyph of Carding",
  "Glyph of Wording",
  "Glyph of Wadding",
  "Glyph of Warming",
  "Glyph of Warning",
  "Glyph of Warping",
  "Glyph of Warring",
  "Rasping Vine",
  "Gasping Vine",
  "Grasping Vie",
  "Grasping Cine",
  "Grasping Dine",
  "Grasping Fine",
  "Grasping Line",
  "Grasping Mine",
  "Grasping Nine",
  "Grasping Pine",
  "Grasping Sine",
  "Grasping Wine",
  "Grasping Vane",
  "Grasping Vice",
  "Grasping Vile",
  "Grasping Vise",
  "Grasping Vino",
  "Crease",
  "Greasy",
  "Grater Invisibility",
  "Grater Restoration",
  "Green-Flame Lade",
  "Green-Flame Bade",
  "Green-Flame Glade",
  "Green-Flame Blame",
  "Green-Flame Blare",
  "Green-Flame Blase",
  "Green-Flame Blaze",
  "Guardian Oaf Faith",
  "Guardian Off Faith",
  "Guardian Off Faith",
  "Guardian If Faith",
  "Guardian Oh Faith",
  "Guardian On Faith",
  "Guardian Or Faith",
  "Guardian Ow Faith",
  "Guardian Ox Faith",
  "Guardian Oaf Nature",
  "Guardian Off Nature",
  "Guardian Off Nature",
  "Guardian If Nature",
  "Guardian Oh Nature",
  "Guardian On Nature",
  "Guardian Or Nature",
  "Guardian Ow Nature",
  "Guardian Ox Nature",
  "Guardian of Mature",
  "Guards Band Wards",
  "Guards Hand Wards",
  "Guards Land Wards",
  "Guards Rand Wards",
  "Guards Sand Wards",
  "Guards Wand Wards",
  "Guards An Wards",
  "Guards End Wards",
  "Guards Add Wards",
  "Guards Aid Wards",
  "Guards Ant Wards",
  "Guards Any Wards",
  "Guards and Awards",
  "Guards and Wads",
  "Guards and Wars",
  "Guards and Bards",
  "Guards and Cards",
  "Guards and Lards",
  "Guards and Yards",
  "Guards and Words",
  "Guards and Wands",
  "Guards and Wares",
  "Guards and Warms",
  "Guards and Warns",
  "Guards and Warps",
  "Guards and Warts",
  "Gliding Bolt",
  "Guiding Colt",
  "Guiding Dolt",
  "Guiding Jolt",
  "Guiding Volt",
  "Guiding Belt",
  "Guiding Boat",
  "Guiding Boot",
  "Guiding Bout",
  "Guiding Bola",
  "Guiding Bold",
  "Guiding Bole",
  "Guiding Blot",
  "Guest",
  "Gusto",
  "Gusty",
  "Gut",
  "Bust",
  "Dust",
  "Just",
  "Lust",
  "Must",
  "Oust",
  "Rust",
  "Gist",
  "Gush",
  "Guts",
  "Guest of Wind",
  "Gusto of Wind",
  "Gusty of Wind",
  "Gut of Wind",
  "Bust of Wind",
  "Dust of Wind",
  "Just of Wind",
  "Lust of Wind",
  "Must of Wind",
  "Oust of Wind",
  "Rust of Wind",
  "Gist of Wind",
  "Gush of Wind",
  "Guts of Wind",
  "Gust Oaf Wind",
  "Gust Off Wind",
  "Gust Off Wind",
  "Gust If Wind",
  "Gust Oh Wind",
  "Gust On Wind",
  "Gust Or Wind",
  "Gust Ow Wind",
  "Gust Ox Wind",
  "Gust of Wined",
  "Gust of Windy",
  "Gust of Win",
  "Gust of Bind",
  "Gust of Find",
  "Gust of Hind",
  "Gust of Kind",
  "Gust of Mind",
  "Gust of Rind",
  "Gust of Wand",
  "Gust of Wend",
  "Gust of Wild",
  "Gust of Wine",
  "Gust of Wing",
  "Gust of Wink",
  "Gust of Wins",
  "Ail of Thorns",
  "Bail of Thorns",
  "Fail of Thorns",
  "Jail of Thorns",
  "Mail of Thorns",
  "Nail of Thorns",
  "Pail of Thorns",
  "Rail of Thorns",
  "Sail of Thorns",
  "Tail of Thorns",
  "Wail of Thorns",
  "Hall of Thorns",
  "Haul of Thorns",
  "Hair of Thorns",
  "Hail Oaf Thorns",
  "Hail Off Thorns",
  "Hail Off Thorns",
  "Hail If Thorns",
  "Hail Oh Thorns",
  "Hail On Thorns",
  "Hail Or Thorns",
  "Hail Ow Thorns",
  "Hail Ox Thorns",
  "Hail of Horns",
  "Hail of Thorny",
  "Shallow",
  "Allow",
  "Hallo",
  "Callow",
  "Fallow",
  "Mallow",
  "Sallow",
  "Tallow",
  "Wallow",
  "Hollow",
  "Hallucinatory Terrapin",
  "Charm",
  "Harem",
  "Arm",
  "Ham",
  "Farm",
  "Warm",
  "Herm",
  "Hard",
  "Hare",
  "Hark",
  "Harp",
  "Hart",
  "Chaste",
  "Hasten",
  "Hate",
  "Baste",
  "Caste",
  "Paste",
  "Taste",
  "Waste",
  "Hasty",
  "Deal",
  "Meal",
  "Peal",
  "Real",
  "Seal",
  "Teal",
  "Veal",
  "Weal",
  "Zeal",
  "Heel",
  "Hell",
  "Head",
  "Heap",
  "Hear",
  "Heat",
  "Dealing Spirit",
  "Pealing Spirit",
  "Sealing Spirit",
  "Heading Spirit",
  "Heaping Spirit",
  "Hearing Spirit",
  "Heating Spirit",
  "Heaving Spirit",
  "Dealing Word",
  "Pealing Word",
  "Sealing Word",
  "Heading Word",
  "Heaping Word",
  "Hearing Word",
  "Heating Word",
  "Heaving Word",
  "Healing World",
  "Healing Sword",
  "Healing Wordy",
  "Healing Cord",
  "Healing Ford",
  "Healing Lord",
  "Healing Ward",
  "Healing Woad",
  "Healing Wold",
  "Healing Wood",
  "Healing Wore",
  "Healing Work",
  "Healing Worm",
  "Healing Worn",
  "Cheat Metal",
  "Heath Metal",
  "Heart Metal",
  "Wheat Metal",
  "Eat Metal",
  "Hat Metal",
  "Beat Metal",
  "Feat Metal",
  "Leat Metal",
  "Meat Metal",
  "Neat Metal",
  "Peat Metal",
  "Seat Metal",
  "Teat Metal",
  "Heft Metal",
  "Head Metal",
  "Heal Metal",
  "Heap Metal",
  "Hear Metal",
  "Heat Mental",
  "Heat Etal",
  "Heat Meal",
  "Heat Fetal",
  "Heat Petal",
  "Heat Medal",
  "Heroes' East",
  "Heroes' Fast",
  "Heroes' Fest",
  "Heroes' Feat",
  "Heroes' Beast",
  "Heroes' Least",
  "Heroes' Yeast",
  "Heroes' Feats",
  "He",
  "Sex",
  "Vex",
  "Hem",
  "Hen",
  "Her",
  "Hew",
  "Hey",
  "Holed Monster",
  "Old Monster",
  "Hod Monster",
  "Bold Monster",
  "Cold Monster",
  "Fold Monster",
  "Gold Monster",
  "Mold Monster",
  "Sold Monster",
  "Told Monster",
  "Wold Monster",
  "Held Monster",
  "Hoed Monster",
  "Hood Monster",
  "Hole Monster",
  "Holy Monster",
  "Hold Minster",
  "Hold Mobster",
  "Hold Moister",
  "Holed Person",
  "Old Person",
  "Hod Person",
  "Bold Person",
  "Cold Person",
  "Fold Person",
  "Gold Person",
  "Mold Person",
  "Sold Person",
  "Told Person",
  "Wold Person",
  "Held Person",
  "Hoed Person",
  "Hood Person",
  "Hole Person",
  "Holy Person",
  "Hold Persona",
  "Hold Parson",
  "Hold Perron",
  "Holly Aura",
  "Holly Aura",
  "Hotly Aura",
  "Homy Aura",
  "Hold Aura",
  "Hole Aura",
  "Holy Aural",
  "Holly Weapon",
  "Holly Weapon",
  "Hotly Weapon",
  "Homy Weapon",
  "Hold Weapon",
  "Hole Weapon",
  "Hanger of Hadar",
  "Hunter of Hadar",
  "Hunger Oaf Hadar",
  "Hunger Off Hadar",
  "Hunger Off Hadar",
  "Hunger If Hadar",
  "Hunger Oh Hadar",
  "Hunger On Hadar",
  "Hunger Or Hadar",
  "Hunger Ow Hadar",
  "Hunger Ox Hadar",
  "Hunger of Radar",
  "Hunter's Ark",
  "Hunter's Mar",
  "Hunter's Bark",
  "Hunter's Dark",
  "Hunter's Hark",
  "Hunter's Lark",
  "Hunter's Park",
  "Hunter's Murk",
  "Hunter's Mask",
  "Hunter's Mara",
  "Hunter's Mare",
  "Hunter's Marl",
  "Hunter's Mars",
  "Hunter's Mart",
  "Hunter's Marx",
  "Hunter's Mary",
  "Hypnotic Patten",
  "Hypnotic Patter",
  "Hypnotic Patters",
  "Dice Knife",
  "Lice Knife",
  "Mice Knife",
  "Nice Knife",
  "Rice Knife",
  "Vice Knife",
  "Ace Knife",
  "Ire Knife",
  "Ive Knife",
  "Icy Knife",
  "Dice Storm",
  "Lice Storm",
  "Mice Storm",
  "Nice Storm",
  "Rice Storm",
  "Vice Storm",
  "Ace Storm",
  "Ire Storm",
  "Ive Storm",
  "Icy Storm",
  "Ice Stormy",
  "Ice Store",
  "Ice Stork",
  "Ice Story",
  "Identity",
  "Illusory Dragoon",
  "Illusory Dragoon",
  "Immoveable Object",
  "Immovable Abject",
  "Incendiary Cloudy",
  "Incendiary Loud",
  "Incendiary Clod",
  "Incendiary Aloud",
  "Incendiary Clout",
  "Inciter Greed",
  "Indite Greed",
  "Invite Greed",
  "Incite Agreed",
  "Incite Greyed",
  "Incite Greedy",
  "Incite Reed",
  "Incite Breed",
  "Incite Creed",
  "Incite Freed",
  "Incite Greek",
  "Incite Green",
  "Incite Greet",
  "Internal Calling",
  "Infernal Falling",
  "Infernal Galling",
  "Infernal Walling",
  "Infernal Culling",
  "Infernal Cabling",
  "Infernal Calming",
  "Infernal Calving",
  "Inflect Wounds",
  "Inflict Bounds",
  "Inflict Founds",
  "Inflict Hounds",
  "Inflict Mounds",
  "Inflict Pounds",
  "Inflict Rounds",
  "Inflict Sounds",
  "Inspect Plague",
  "Inset Plague",
  "Infect Plague",
  "Inject Plague",
  "Insert Plague",
  "Insect Prague",
  "Insect Plaque",
  "Investiture Oaf Flame",
  "Investiture Off Flame",
  "Investiture Off Flame",
  "Investiture If Flame",
  "Investiture Oh Flame",
  "Investiture On Flame",
  "Investiture Or Flame",
  "Investiture Ow Flame",
  "Investiture Ox Flame",
  "Investiture of Aflame",
  "Investiture of Lame",
  "Investiture of Fame",
  "Investiture of Blame",
  "Investiture of Frame",
  "Investiture of Flake",
  "Investiture of Flare",
  "Investiture Oaf Ice",
  "Investiture Off Ice",
  "Investiture Off Ice",
  "Investiture If Ice",
  "Investiture Oh Ice",
  "Investiture On Ice",
  "Investiture Or Ice",
  "Investiture Ow Ice",
  "Investiture Ox Ice",
  "Investiture of Dice",
  "Investiture of Lice",
  "Investiture of Mice",
  "Investiture of Nice",
  "Investiture of Rice",
  "Investiture of Vice",
  "Investiture of Ace",
  "Investiture of Ire",
  "Investiture of Ive",
  "Investiture of Icy",
  "Investiture Oaf Stone",
  "Investiture Off Stone",
  "Investiture Off Stone",
  "Investiture If Stone",
  "Investiture Oh Stone",
  "Investiture On Stone",
  "Investiture Or Stone",
  "Investiture Ow Stone",
  "Investiture Ox Stone",
  "Investiture of Tone",
  "Investiture of Atone",
  "Investiture of Scone",
  "Investiture of Shone",
  "Investiture of Stoke",
  "Investiture of Stole",
  "Investiture of Store",
  "Investiture of Stove",
  "Investiture of Stony",
  "Investiture Oaf Wind",
  "Investiture Off Wind",
  "Investiture Off Wind",
  "Investiture If Wind",
  "Investiture Oh Wind",
  "Investiture On Wind",
  "Investiture Or Wind",
  "Investiture Ow Wind",
  "Investiture Ox Wind",
  "Investiture of Wined",
  "Investiture of Windy",
  "Investiture of Win",
  "Investiture of Bind",
  "Investiture of Find",
  "Investiture of Hind",
  "Investiture of Kind",
  "Investiture of Mind",
  "Investiture of Rind",
  "Investiture of Wand",
  "Investiture of Wend",
  "Investiture of Wild",
  "Investiture of Wine",
  "Investiture of Wing",
  "Investiture of Wink",
  "Investiture of Wins",
  "Jim's Lowing Coin",
  "Jim's Blowing Coin",
  "Jim's Flowing Coin",
  "Jim's Slowing Coin",
  "Jim's Growing Coin",
  "Jim's Glowing Con",
  "Jim's Glowing Join",
  "Jim's Glowing Loin",
  "Jim's Glowing Cain",
  "Jim's Glowing Chin",
  "Jim's Glowing Coon",
  "Jim's Glowing Corn",
  "Jim's Glowing Coil",
  "Jim's Magi Missile",
  "Jim's Manic Missile",
  "Jim's Magic Fissile",
  "Jim's Magic Missive",
  "Jumpy",
  "Bump",
  "Dump",
  "Hump",
  "Lump",
  "Pump",
  "Rump",
  "Sump",
  "Knack",
  "Legend Loire",
  "Legend Ore",
  "Legend Bore",
  "Legend Core",
  "Legend Fore",
  "Legend Gore",
  "Legend More",
  "Legend Pore",
  "Legend Sore",
  "Legend Tore",
  "Legend Wore",
  "Legend Yore",
  "Legend Lire",
  "Legend Lure",
  "Legend Lyre",
  "Legend Lobe",
  "Legend Lode",
  "Legend Lone",
  "Legend Lope",
  "Legend Lose",
  "Legend Love",
  "Legend Lord",
  "Leomund's Secrete Chest",
  "Leomund's Secret Chesty",
  "Leomund's Secret Crest",
  "Leomund's Secret Cheat",
  "Leomund's Secret Chess",
  "Leomund's Tinny Hut",
  "Leomund's Tinny Hut",
  "Leomund's Tin Hut",
  "Leomund's Liny Hut",
  "Leomund's Piny Hut",
  "Leomund's Tony Hut",
  "Leomund's Tidy Hut",
  "Leomund's Tins Hut",
  "Leomund's Tint Hut",
  "Leomund's Tiny Hunt",
  "Leomund's Tiny Hurt",
  "Leomund's Tiny Shut",
  "Leomund's Tiny But",
  "Leomund's Tiny Cut",
  "Leomund's Tiny Gut",
  "Leomund's Tiny Jut",
  "Leomund's Tiny Nut",
  "Leomund's Tiny Out",
  "Leomund's Tiny Put",
  "Leomund's Tiny Rut",
  "Leomund's Tiny Hat",
  "Leomund's Tiny Hit",
  "Leomund's Tiny Hot",
  "Leomund's Tiny Hub",
  "Leomund's Tiny Hue",
  "Leomund's Tiny Hug",
  "Leomund's Tiny Huh",
  "Leomund's Tiny Hum",
  "Lessor Restoration",
  "Lessee Restoration",
  "Lessen Restoration",
  "Lie Transference",
  "Fife Transference",
  "Rife Transference",
  "Wife Transference",
  "Lice Transference",
  "Like Transference",
  "Lime Transference",
  "Line Transference",
  "Lire Transference",
  "Live Transference",
  "Lift Transference",
  "Alight",
  "Blight",
  "Flight",
  "Plight",
  "Slight",
  "Eight",
  "Fight",
  "Hight",
  "Might",
  "Night",
  "Right",
  "Sight",
  "Tight",
  "Lightening Arrow",
  "Lighting Arrow",
  "Lightning Barrow",
  "Lightning Farrow",
  "Lightning Harrow",
  "Lightning Marrow",
  "Lightning Narrow",
  "Lightening Bolt",
  "Lighting Bolt",
  "Lightning Colt",
  "Lightning Dolt",
  "Lightning Jolt",
  "Lightning Volt",
  "Lightning Belt",
  "Lightning Boat",
  "Lightning Boot",
  "Lightning Bout",
  "Lightning Bola",
  "Lightning Bold",
  "Lightning Bole",
  "Lightning Blot",
  "Lightening Lure",
  "Lighting Lure",
  "Lightning Lucre",
  "Lightning Lurex",
  "Lightning Lur",
  "Lightning Cure",
  "Lightning Pure",
  "Lightning Sure",
  "Lightning Lire",
  "Lightning Lore",
  "Lightning Lyre",
  "Lightning Luke",
  "Lightning Lune",
  "Lightning Lute",
  "Lightning Lurk",
  "Blinked Glyphs",
  "Clinked Glyphs",
  "Inked Glyphs",
  "Liked Glyphs",
  "Lined Glyphs",
  "Jinked Glyphs",
  "Kinked Glyphs",
  "Oinked Glyphs",
  "Pinked Glyphs",
  "Winked Glyphs",
  "Licked Glyphs",
  "Linker Glyphs",
  "Locale Animals or Plants",
  "Locate Animals Oar Plants",
  "Locate Animals Orb Plants",
  "Locate Animals Ore Plants",
  "Locate Animals For Plants",
  "Locate Animals Nor Plants",
  "Locate Animals Our Plants",
  "Locate Animals Dr Plants",
  "Locate Animals Mr Plants",
  "Locate Animals Of Plants",
  "Locate Animals Oh Plants",
  "Locate Animals On Plants",
  "Locate Animals Ow Plants",
  "Locate Animals Ox Plants",
  "Locate Animals or Planets",
  "Locate Animals or Pants",
  "Locate Animals or Plans",
  "Locate Animals or Slants",
  "Locate Animals or Plaits",
  "Locate Animals or Planes",
  "Locate Animals or Planks",
  "Locale Creature",
  "Locale Object",
  "Locate Abject",
  "Saddening Darkness",
  "Image Armor",
  "Mange Armor",
  "Age Armor",
  "Mag Armor",
  "Cage Armor",
  "Gage Armor",
  "Page Armor",
  "Rage Armor",
  "Sage Armor",
  "Wage Armor",
  "Mace Armor",
  "Made Armor",
  "Make Armor",
  "Male Armor",
  "Mane Armor",
  "Mare Armor",
  "Mate Armor",
  "Maze Armor",
  "Magi Armor",
  "Mags Armor",
  "Mage Armour",
  "Mage Arbor",
  "Image Hand",
  "Mange Hand",
  "Age Hand",
  "Mag Hand",
  "Cage Hand",
  "Gage Hand",
  "Page Hand",
  "Rage Hand",
  "Sage Hand",
  "Wage Hand",
  "Mace Hand",
  "Made Hand",
  "Make Hand",
  "Male Hand",
  "Mane Hand",
  "Mare Hand",
  "Mate Hand",
  "Maze Hand",
  "Magi Hand",
  "Mags Hand",
  "Mage Handy",
  "Mage And",
  "Mage Had",
  "Mage Band",
  "Mage Land",
  "Mage Rand",
  "Mage Sand",
  "Mage Wand",
  "Mage Hind",
  "Mage Hard",
  "Mage Hang",
  "Magi Circle",
  "Manic Circle",
  "Magic Circlet",
  "Magi Jar",
  "Manic Jar",
  "Magic Ajar",
  "Magic Jarl",
  "Magic Bar",
  "Magic Car",
  "Magic Ear",
  "Magic Far",
  "Magic Mar",
  "Magic Oar",
  "Magic Par",
  "Magic Tar",
  "Magic War",
  "Magic Jab",
  "Magic Jag",
  "Magic Jam",
  "Magic Jap",
  "Magic Jaw",
  "Magic Jay",
  "Magi Missile",
  "Manic Missile",
  "Magic Fissile",
  "Magic Missive",
  "Magi Mouth",
  "Manic Mouth",
  "Magic Moth",
  "Magic South",
  "Magic Youth",
  "Magic Month",
  "Magi Stone",
  "Manic Stone",
  "Magic Tone",
  "Magic Atone",
  "Magic Scone",
  "Magic Shone",
  "Magic Stoke",
  "Magic Stole",
  "Magic Store",
  "Magic Stove",
  "Magic Stony",
  "Magi Weapon",
  "Manic Weapon",
  "Manor Image",
  "Mayor Image",
  "Major Imago",
  "Amass Cure Wounds",
  "Masks Cure Wounds",
  "Masts Cure Wounds",
  "Ass Cure Wounds",
  "Bass Cure Wounds",
  "Lass Cure Wounds",
  "Pass Cure Wounds",
  "Mess Cure Wounds",
  "Miss Cure Wounds",
  "Moss Cure Wounds",
  "Mags Cure Wounds",
  "Maps Cure Wounds",
  "Mars Cure Wounds",
  "Mats Cure Wounds",
  "Mash Cure Wounds",
  "Mask Cure Wounds",
  "Mast Cure Wounds",
  "Mass Curie Wounds",
  "Mass Curer Wounds",
  "Mass Curse Wounds",
  "Mass Curve Wounds",
  "Mass Cue Wounds",
  "Mass Cur Wounds",
  "Mass Lure Wounds",
  "Mass Pure Wounds",
  "Mass Sure Wounds",
  "Mass Care Wounds",
  "Mass Core Wounds",
  "Mass Cube Wounds",
  "Mass Cute Wounds",
  "Mass Curb Wounds",
  "Mass Curd Wounds",
  "Mass Curl Wounds",
  "Mass Curs Wounds",
  "Mass Curt Wounds",
  "Mass Cure Bounds",
  "Mass Cure Founds",
  "Mass Cure Hounds",
  "Mass Cure Mounds",
  "Mass Cure Pounds",
  "Mass Cure Rounds",
  "Mass Cure Sounds",
  "Amass Heal",
  "Masks Heal",
  "Masts Heal",
  "Ass Heal",
  "Bass Heal",
  "Lass Heal",
  "Pass Heal",
  "Mess Heal",
  "Miss Heal",
  "Moss Heal",
  "Mags Heal",
  "Maps Heal",
  "Mars Heal",
  "Mats Heal",
  "Mash Heal",
  "Mask Heal",
  "Mast Heal",
  "Mass Deal",
  "Mass Meal",
  "Mass Peal",
  "Mass Real",
  "Mass Seal",
  "Mass Teal",
  "Mass Veal",
  "Mass Weal",
  "Mass Zeal",
  "Mass Heel",
  "Mass Hell",
  "Mass Head",
  "Mass Heap",
  "Mass Hear",
  "Mass Heat",
  "Amass Healing Word",
  "Masks Healing Word",
  "Masts Healing Word",
  "Ass Healing Word",
  "Bass Healing Word",
  "Lass Healing Word",
  "Pass Healing Word",
  "Mess Healing Word",
  "Miss Healing Word",
  "Moss Healing Word",
  "Mags Healing Word",
  "Maps Healing Word",
  "Mars Healing Word",
  "Mats Healing Word",
  "Mash Healing Word",
  "Mask Healing Word",
  "Mast Healing Word",
  "Mass Dealing Word",
  "Mass Pealing Word",
  "Mass Sealing Word",
  "Mass Heading Word",
  "Mass Heaping Word",
  "Mass Hearing Word",
  "Mass Heating Word",
  "Mass Heaving Word",
  "Mass Healing World",
  "Mass Healing Sword",
  "Mass Healing Wordy",
  "Mass Healing Cord",
  "Mass Healing Ford",
  "Mass Healing Lord",
  "Mass Healing Ward",
  "Mass Healing Woad",
  "Mass Healing Wold",
  "Mass Healing Wood",
  "Mass Healing Wore",
  "Mass Healing Work",
  "Mass Healing Worm",
  "Mass Healing Worn",
  "Amass Polymorph",
  "Masks Polymorph",
  "Masts Polymorph",
  "Ass Polymorph",
  "Bass Polymorph",
  "Lass Polymorph",
  "Pass Polymorph",
  "Mess Polymorph",
  "Miss Polymorph",
  "Moss Polymorph",
  "Mags Polymorph",
  "Maps Polymorph",
  "Mars Polymorph",
  "Mats Polymorph",
  "Mash Polymorph",
  "Mask Polymorph",
  "Mast Polymorph",
  "Amass Suggestion",
  "Masks Suggestion",
  "Masts Suggestion",
  "Ass Suggestion",
  "Bass Suggestion",
  "Lass Suggestion",
  "Pass Suggestion",
  "Mess Suggestion",
  "Miss Suggestion",
  "Moss Suggestion",
  "Mags Suggestion",
  "Maps Suggestion",
  "Mars Suggestion",
  "Mats Suggestion",
  "Mash Suggestion",
  "Mask Suggestion",
  "Mast Suggestion",
  "Maximilian's Earthed Grasp",
  "Maximilian's Earthen Rasp",
  "Maximilian's Earthen Gasp",
  "Maximilian's Earthen Grass",
  "Amaze",
  "Maize",
  "Daze",
  "Gaze",
  "Haze",
  "Laze",
  "Raze",
  "Mace",
  "Made",
  "Make",
  "Male",
  "Mane",
  "Mare",
  "Mate",
  "Mazy",
  "Held into Stone",
  "Veld into Stone",
  "Weld into Stone",
  "Mild into Stone",
  "Mold into Stone",
  "Mead into Stone",
  "Mend into Stone",
  "Melt into Stone",
  "Meld Intro Stone",
  "Meld Onto Stone",
  "Meld Unto Stone",
  "Meld Info Stone",
  "Meld into Tone",
  "Meld into Atone",
  "Meld into Scone",
  "Meld into Shone",
  "Meld into Stoke",
  "Meld into Stole",
  "Meld into Store",
  "Meld into Stove",
  "Meld into Stony",
  "Melf's Acrid Arrow",
  "Melf's Aid Arrow",
  "Melf's Amid Arrow",
  "Melf's Arid Arrow",
  "Melf's Avid Arrow",
  "Melf's Aced Arrow",
  "Melf's Acid Barrow",
  "Melf's Acid Farrow",
  "Melf's Acid Harrow",
  "Melf's Acid Marrow",
  "Melf's Acid Narrow",
  "Melf's Minuet Meteors",
  "Melf's Minute Meters",
  "Amending",
  "Ending",
  "Bending",
  "Fending",
  "Lending",
  "Pending",
  "Rending",
  "Sending",
  "Tending",
  "Vending",
  "Wending",
  "Minding",
  "Metal Prison",
  "Dental Prison",
  "Rental Prison",
  "Menial Prison",
  "Mental Poison",
  "Massage",
  "Meter Swarm",
  "Meteor Warm",
  "Meteor Swam",
  "Meteor Sward",
  "Might Fortress",
  "Eighty Fortress",
  "Mights Fortress",
  "Mined Blank",
  "Mid Blank",
  "Bind Blank",
  "Find Blank",
  "Hind Blank",
  "Kind Blank",
  "Rind Blank",
  "Wind Blank",
  "Mend Blank",
  "Mild Blank",
  "Mine Blank",
  "Mini Blank",
  "Mink Blank",
  "Mint Blank",
  "Minx Blank",
  "Mind Lank",
  "Mind Bank",
  "Mind Clank",
  "Mind Flank",
  "Mind Plank",
  "Mind Blink",
  "Mind Black",
  "Mind Bland",
  "Mined Sliver",
  "Mid Sliver",
  "Bind Sliver",
  "Find Sliver",
  "Hind Sliver",
  "Kind Sliver",
  "Rind Sliver",
  "Wind Sliver",
  "Mend Sliver",
  "Mild Sliver",
  "Mine Sliver",
  "Mini Sliver",
  "Mink Sliver",
  "Mint Sliver",
  "Minx Sliver",
  "Mind Liver",
  "Mind Oliver",
  "Mind Shiver",
  "Mind Slaver",
  "Mind Slicer",
  "Mind Slider",
  "Mind Silver",
  "Mined Spike",
  "Mid Spike",
  "Bind Spike",
  "Find Spike",
  "Hind Spike",
  "Kind Spike",
  "Rind Spike",
  "Wind Spike",
  "Mend Spike",
  "Mild Spike",
  "Mine Spike",
  "Mini Spike",
  "Mink Spike",
  "Mint Spike",
  "Minx Spike",
  "Mind Pike",
  "Mind Spoke",
  "Mind Spice",
  "Mind Spine",
  "Mind Spire",
  "Mind Spite",
  "Mind Spiky",
  "Manor Illusion",
  "Miner Illusion",
  "Minor Allusion",
  "Mirage Arcade",
  "Mirage Arcana",
  "Mirror Imago",
  "Misled",
  "Misread",
  "Mist Step",
  "Musty Step",
  "Minty Step",
  "Missy Step",
  "Mists Step",
  "Misty Steep",
  "Misty Steep",
  "Misty Stoep",
  "Misty Seep",
  "Misty Stop",
  "Misty Stem",
  "Misty Stet",
  "Misty Stew",
  "Codify Memory",
  "Mould Earth",
  "Moldy Earth",
  "Old Earth",
  "Mod Earth",
  "Bold Earth",
  "Cold Earth",
  "Fold Earth",
  "Gold Earth",
  "Hold Earth",
  "Sold Earth",
  "Told Earth",
  "Wold Earth",
  "Meld Earth",
  "Mild Earth",
  "Mood Earth",
  "Mole Earth",
  "Mold Dearth",
  "Mold Hearth",
  "Mold Earthy",
  "Mordenkainen's Faithful Bound",
  "Mordenkainen's Faithful Found",
  "Mordenkainen's Faithful Mound",
  "Mordenkainen's Faithful Pound",
  "Mordenkainen's Faithful Round",
  "Mordenkainen's Faithful Sound",
  "Mordenkainen's Faithful Wound",
  "Mordenkainen's Primate Sanctum",
  "Mordenkainen's Word",
  "Mordenkainen's Sward",
  "Mordenkainen's Swore",
  "Mordenkainen's Sworn",
  "Movie Earth",
  "Mover Earth",
  "Cove Earth",
  "Dove Earth",
  "Hove Earth",
  "Love Earth",
  "Rove Earth",
  "Wove Earth",
  "Mode Earth",
  "Mole Earth",
  "Mope Earth",
  "More Earth",
  "Move Dearth",
  "Move Hearth",
  "Move Earthy",
  "Negative Anergy Flood",
  "Negative Energy Food",
  "Negative Energy Blood",
  "Negative Energy Floor",
  "Nystul's Magi Aura",
  "Nystul's Manic Aura",
  "Nystul's Magic Aural",
  "Otiluke's Freeing Sphere",
  "Otiluke's Breezing Sphere",
  "Otto's Irresistibly Dance",
  "Otto's Irresistible Dancer",
  "Otto's Irresistible Dace",
  "Otto's Irresistible Dane",
  "Otto's Irresistible Lance",
  "Otto's Irresistible Dunce",
  "Otto's Irresistible Dante",
  "Passe without Trace",
  "Pasts without Trace",
  "Ass without Trace",
  "Bass without Trace",
  "Lass without Trace",
  "Mass without Trace",
  "Puss without Trace",
  "Pads without Trace",
  "Pals without Trace",
  "Pans without Trace",
  "Pats without Trace",
  "Paws without Trace",
  "Pays without Trace",
  "Past without Trace",
  "Pass without Trance",
  "Pass without Tracer",
  "Pass without Race",
  "Pass without Brace",
  "Pass without Grace",
  "Pass without Trice",
  "Pass without Truce",
  "Pass without Trade",
  "Pass without Track",
  "Pass without Tract",
  "Phantasmal Fore",
  "Phantasmal Farce",
  "Phantasmal Forge",
  "Phantasmal Forte",
  "Phantasmal Filler",
  "Phantasmal Miller",
  "Phantasmal Tiller",
  "Phantasmal Kilter",
  "Phantasmal Killed",
  "Phantom Stewed",
  "Phantom Teed",
  "Phantom Seed",
  "Phantom Speed",
  "Phantom Stead",
  "Phantom Steel",
  "Phantom Steep",
  "Phantom Steer",
  "Planar Allay",
  "Planar Dally",
  "Planar Alley",
  "Planar Alloy",
  "Planar Rally",
  "Planar Sally",
  "Planar Tally",
  "Planar All",
  "Planar Ably",
  "Planar Blinding",
  "Planar Biding",
  "Planar Finding",
  "Planar Minding",
  "Planar Winding",
  "Planar Banding",
  "Planar Bending",
  "Planar Bonding",
  "Planar Bidding",
  "Planet Shift",
  "Lane Shift",
  "Pane Shift",
  "Plan Shift",
  "Place Shift",
  "Plate Shift",
  "Plank Shift",
  "Plans Shift",
  "Plant Shift",
  "Plane Shrift",
  "Plane Shifty",
  "Plane Sift",
  "Plane Shit",
  "Plane Swift",
  "Plane Shaft",
  "Plane Shirt",
  "Planet Growth",
  "Pliant Growth",
  "Plaint Growth",
  "Pant Growth",
  "Plan Growth",
  "Slant Growth",
  "Plait Growth",
  "Plane Growth",
  "Plank Growth",
  "Plans Growth",
  "Prison Spray",
  "Poison Pray",
  "Poison Spay",
  "Poison Spry",
  "Poison Stray",
  "Poison Sprat",
  "Powder Word Heal",
  "Bower Word Heal",
  "Cower Word Heal",
  "Lower Word Heal",
  "Mower Word Heal",
  "Rower Word Heal",
  "Sower Word Heal",
  "Tower Word Heal",
  "Poker Word Heal",
  "Poser Word Heal",
  "Power World Heal",
  "Power Sword Heal",
  "Power Wordy Heal",
  "Power Cord Heal",
  "Power Ford Heal",
  "Power Lord Heal",
  "Power Ward Heal",
  "Power Woad Heal",
  "Power Wold Heal",
  "Power Wood Heal",
  "Power Wore Heal",
  "Power Work Heal",
  "Power Worm Heal",
  "Power Worn Heal",
  "Power Word Deal",
  "Power Word Meal",
  "Power Word Peal",
  "Power Word Real",
  "Power Word Seal",
  "Power Word Teal",
  "Power Word Veal",
  "Power Word Weal",
  "Power Word Zeal",
  "Power Word Heel",
  "Power Word Hell",
  "Power Word Head",
  "Power Word Heap",
  "Power Word Hear",
  "Power Word Heat",
  "Powder Word Kill",
  "Bower Word Kill",
  "Cower Word Kill",
  "Lower Word Kill",
  "Mower Word Kill",
  "Rower Word Kill",
  "Sower Word Kill",
  "Tower Word Kill",
  "Poker Word Kill",
  "Poser Word Kill",
  "Power World Kill",
  "Power Sword Kill",
  "Power Wordy Kill",
  "Power Cord Kill",
  "Power Ford Kill",
  "Power Lord Kill",
  "Power Ward Kill",
  "Power Woad Kill",
  "Power Wold Kill",
  "Power Wood Kill",
  "Power Wore Kill",
  "Power Work Kill",
  "Power Worm Kill",
  "Power Worn Kill",
  "Power Word Krill",
  "Power Word Skill",
  "Power Word Ill",
  "Power Word Bill",
  "Power Word Dill",
  "Power Word Fill",
  "Power Word Gill",
  "Power Word Hill",
  "Power Word Mill",
  "Power Word Pill",
  "Power Word Rill",
  "Power Word Till",
  "Power Word Will",
  "Power Word Kiln",
  "Power Word Kilo",
  "Power Word Kilt",
  "Powder Word Pain",
  "Bower Word Pain",
  "Cower Word Pain",
  "Lower Word Pain",
  "Mower Word Pain",
  "Rower Word Pain",
  "Sower Word Pain",
  "Tower Word Pain",
  "Poker Word Pain",
  "Poser Word Pain",
  "Power World Pain",
  "Power Sword Pain",
  "Power Wordy Pain",
  "Power Cord Pain",
  "Power Ford Pain",
  "Power Lord Pain",
  "Power Ward Pain",
  "Power Woad Pain",
  "Power Wold Pain",
  "Power Wood Pain",
  "Power Wore Pain",
  "Power Work Pain",
  "Power Worm Pain",
  "Power Worn Pain",
  "Power Word Plain",
  "Power Word Spain",
  "Power Word Paint",
  "Power Word Pin",
  "Power Word Pan",
  "Power Word Cain",
  "Power Word Gain",
  "Power Word Lain",
  "Power Word Main",
  "Power Word Rain",
  "Power Word Vain",
  "Power Word Pawn",
  "Power Word Paid",
  "Power Word Pail",
  "Power Word Pair",
  "Powder Word Stun",
  "Bower Word Stun",
  "Cower Word Stun",
  "Lower Word Stun",
  "Mower Word Stun",
  "Rower Word Stun",
  "Sower Word Stun",
  "Tower Word Stun",
  "Poker Word Stun",
  "Poser Word Stun",
  "Power World Stun",
  "Power Sword Stun",
  "Power Wordy Stun",
  "Power Cord Stun",
  "Power Ford Stun",
  "Power Lord Stun",
  "Power Ward Stun",
  "Power Woad Stun",
  "Power Wold Stun",
  "Power Wood Stun",
  "Power Wore Stun",
  "Power Work Stun",
  "Power Worm Stun",
  "Power Worn Stun",
  "Power Word Stung",
  "Power Word Stunt",
  "Power Word Tun",
  "Power Word Sun",
  "Power Word Shun",
  "Power Word Spun",
  "Power Word Stub",
  "Power Word Stud",
  "Sprayer of Healing",
  "Payer of Healing",
  "Player of Healing",
  "Prayed of Healing",
  "Prayer Oaf Healing",
  "Prayer Off Healing",
  "Prayer Off Healing",
  "Prayer If Healing",
  "Prayer Oh Healing",
  "Prayer On Healing",
  "Prayer Or Healing",
  "Prayer Ow Healing",
  "Prayer Ox Healing",
  "Prayer of Dealing",
  "Prayer of Pealing",
  "Prayer of Sealing",
  "Prayer of Heading",
  "Prayer of Heaping",
  "Prayer of Hearing",
  "Prayer of Heating",
  "Prayer of Heaving",
  "Primal Savagely",
  "Primordial Award",
  "Primordial Sward",
  "Primordial Wad",
  "Primordial War",
  "Primordial Bard",
  "Primordial Card",
  "Primordial Hard",
  "Primordial Lard",
  "Primordial Yard",
  "Primordial Word",
  "Primordial Wand",
  "Primordial Ware",
  "Primordial Warm",
  "Primordial Warn",
  "Primordial Warp",
  "Primordial Wars",
  "Primordial Wart",
  "Primordial Wary",
  "Prismatic Pray",
  "Prismatic Spay",
  "Prismatic Spry",
  "Prismatic Stray",
  "Prismatic Sprat",
  "Prismatic All",
  "Prismatic Ball",
  "Prismatic Call",
  "Prismatic Fall",
  "Prismatic Gall",
  "Prismatic Hall",
  "Prismatic Mall",
  "Prismatic Pall",
  "Prismatic Tall",
  "Prismatic Well",
  "Prismatic Will",
  "Prismatic Wail",
  "Prismatic Walk",
  "Producer Flame",
  "Product Flame",
  "Produce Aflame",
  "Produce Lame",
  "Produce Fame",
  "Produce Blame",
  "Produce Frame",
  "Produce Flake",
  "Produce Flare",
  "Programme Illusion",
  "Programmer Illusion",
  "Programmes Illusion",
  "Programmed Allusion",
  "Protect Image",
  "Project Imago",
  "Projection from Energy",
  "Protection Rom Energy",
  "Protection Fro Energy",
  "Protection Frog Energy",
  "Protection Form Energy",
  "Protection from Anergy",
  "Projection from Evil and Good",
  "Protection Rom Evil and Good",
  "Protection Fro Evil and Good",
  "Protection Frog Evil and Good",
  "Protection Form Evil and Good",
  "Protection from Devil and Good",
  "Protection from Veil and Good",
  "Protection from Evil Band Good",
  "Protection from Evil Hand Good",
  "Protection from Evil Land Good",
  "Protection from Evil Rand Good",
  "Protection from Evil Sand Good",
  "Protection from Evil Wand Good",
  "Protection from Evil An Good",
  "Protection from Evil End Good",
  "Protection from Evil Add Good",
  "Protection from Evil Aid Good",
  "Protection from Evil Ant Good",
  "Protection from Evil Any Good",
  "Protection from Evil and Goody",
  "Protection from Evil and God",
  "Protection from Evil and God",
  "Protection from Evil and Goo",
  "Protection from Evil and Food",
  "Protection from Evil and Hood",
  "Protection from Evil and Mood",
  "Protection from Evil and Wood",
  "Protection from Evil and Goad",
  "Protection from Evil and Gold",
  "Protection from Evil and Goof",
  "Protection from Evil and Goon",
  "Projection from Poison",
  "Protection Rom Poison",
  "Protection Fro Poison",
  "Protection Frog Poison",
  "Protection Form Poison",
  "Protection from Prison",
  "Psychic Cream",
  "Psychic Scram",
  "Psychic Stream",
  "Purse Wave",
  "Pulse Weave",
  "Pulse Waive",
  "Pulse Waver",
  "Pulse Ave",
  "Pulse Cave",
  "Pulse Gave",
  "Pulse Have",
  "Pulse Nave",
  "Pulse Pave",
  "Pulse Rave",
  "Pulse Save",
  "Pulse Wove",
  "Pulse Wade",
  "Pulse Wage",
  "Pulse Wake",
  "Pulse Wane",
  "Pulse Ware",
  "Pulse Wavy",
  "Purity Food and Drink",
  "Purify Flood and Drink",
  "Purify Good and Drink",
  "Purify Hood and Drink",
  "Purify Mood and Drink",
  "Purify Wood and Drink",
  "Purify Fold and Drink",
  "Purify Fond and Drink",
  "Purify Ford and Drink",
  "Purify Fool and Drink",
  "Purify Foot and Drink",
  "Purify Food Band Drink",
  "Purify Food Hand Drink",
  "Purify Food Land Drink",
  "Purify Food Rand Drink",
  "Purify Food Sand Drink",
  "Purify Food Wand Drink",
  "Purify Food An Drink",
  "Purify Food End Drink",
  "Purify Food Add Drink",
  "Purify Food Aid Drink",
  "Purify Food Ant Drink",
  "Purify Food Any Drink",
  "Purify Food and Rink",
  "Purify Food and Brink",
  "Purify Food and Drank",
  "Purify Food and Drunk",
  "Braise Dead",
  "Praise Dead",
  "Raiser Dead",
  "Rise Dead",
  "Arise Dead",
  "Raise Dread",
  "Raise Dad",
  "Raise Bead",
  "Raise Head",
  "Raise Lead",
  "Raise Mead",
  "Raise Read",
  "Raise Dyad",
  "Raise Deed",
  "Raise Deaf",
  "Raise Deal",
  "Raise Dean",
  "Raise Dear",
  "Rary's Telepathic Boned",
  "Rary's Telepathic Blond",
  "Rary's Telepathic Bound",
  "Rary's Telepathic Fond",
  "Rary's Telepathic Pond",
  "Rary's Telepathic Band",
  "Rary's Telepathic Bend",
  "Rary's Telepathic Bind",
  "Rary's Telepathic Bold",
  "Rary's Telepathic Bone",
  "Rary's Telepathic Bong",
  "Rary's Telepathic Bonn",
  "Rary's Telepathic Bony",
  "Raulothim's Psychic Glance",
  "Raulothim's Psychic Lancer",
  "Raulothim's Psychic Lancet",
  "Raulothim's Psychic Lace",
  "Raulothim's Psychic Lane",
  "Raulothim's Psychic Dance",
  "Ravenous Avoid",
  "Ravenous Ovoid",
  "Bray of Enfeeblement",
  "Racy of Enfeeblement",
  "Dray of Enfeeblement",
  "Fray of Enfeeblement",
  "Pray of Enfeeblement",
  "Tray of Enfeeblement",
  "Xray of Enfeeblement",
  "Bay of Enfeeblement",
  "Day of Enfeeblement",
  "Gay of Enfeeblement",
  "Hay of Enfeeblement",
  "Jay of Enfeeblement",
  "Lay of Enfeeblement",
  "May of Enfeeblement",
  "Nay of Enfeeblement",
  "Pay of Enfeeblement",
  "Say of Enfeeblement",
  "Way of Enfeeblement",
  "Rad of Enfeeblement",
  "Rag of Enfeeblement",
  "Raj of Enfeeblement",
  "Ram of Enfeeblement",
  "Ran of Enfeeblement",
  "Rap of Enfeeblement",
  "Rat of Enfeeblement",
  "Raw of Enfeeblement",
  "Ray Oaf Enfeeblement",
  "Ray Off Enfeeblement",
  "Ray Off Enfeeblement",
  "Ray If Enfeeblement",
  "Ray Oh Enfeeblement",
  "Ray On Enfeeblement",
  "Ray Or Enfeeblement",
  "Ray Ow Enfeeblement",
  "Ray Ox Enfeeblement",
  "Bray of Frost",
  "Racy of Frost",
  "Dray of Frost",
  "Fray of Frost",
  "Pray of Frost",
  "Tray of Frost",
  "Xray of Frost",
  "Bay of Frost",
  "Day of Frost",
  "Gay of Frost",
  "Hay of Frost",
  "Jay of Frost",
  "Lay of Frost",
  "May of Frost",
  "Nay of Frost",
  "Pay of Frost",
  "Say of Frost",
  "Way of Frost",
  "Rad of Frost",
  "Rag of Frost",
  "Raj of Frost",
  "Ram of Frost",
  "Ran of Frost",
  "Rap of Frost",
  "Rat of Frost",
  "Raw of Frost",
  "Ray Oaf Frost",
  "Ray Off Frost",
  "Ray Off Frost",
  "Ray If Frost",
  "Ray Oh Frost",
  "Ray On Frost",
  "Ray Or Frost",
  "Ray Ow Frost",
  "Ray Ox Frost",
  "Ray of Frosty",
  "Ray of Front",
  "Bray of Sickness",
  "Racy of Sickness",
  "Dray of Sickness",
  "Fray of Sickness",
  "Pray of Sickness",
  "Tray of Sickness",
  "Xray of Sickness",
  "Bay of Sickness",
  "Day of Sickness",
  "Gay of Sickness",
  "Hay of Sickness",
  "Jay of Sickness",
  "Lay of Sickness",
  "May of Sickness",
  "Nay of Sickness",
  "Pay of Sickness",
  "Say of Sickness",
  "Way of Sickness",
  "Rad of Sickness",
  "Rag of Sickness",
  "Raj of Sickness",
  "Ram of Sickness",
  "Ran of Sickness",
  "Rap of Sickness",
  "Rat of Sickness",
  "Raw of Sickness",
  "Ray Oaf Sickness",
  "Ray Off Sickness",
  "Ray Off Sickness",
  "Ray If Sickness",
  "Ray Oh Sickness",
  "Ray On Sickness",
  "Ray Or Sickness",
  "Ray Ow Sickness",
  "Ray Ox Sickness",
  "Ray of Slickness",
  "Regality Break",
  "Realty Break",
  "Reality Beak",
  "Reality Creak",
  "Reality Freak",
  "Reality Wreak",
  "Reality Bleak",
  "Reality Bread",
  "Reality Bream",
  "Degenerate",
  "Remover Curse",
  "Remote Curse",
  "Remove Course",
  "Remove Cure",
  "Remove Curs",
  "Remove Nurse",
  "Remove Purse",
  "Remove Corse",
  "Remove Curie",
  "Remove Curve",
  "Remove Cures",
  "Reverser Gravity",
  "Revere Gravity",
  "Reverie Gravity",
  "Reveres Gravity",
  "Rime's Blinding Ice",
  "Rime's Biding Ice",
  "Rime's Finding Ice",
  "Rime's Minding Ice",
  "Rime's Winding Ice",
  "Rime's Banding Ice",
  "Rime's Bending Ice",
  "Rime's Bonding Ice",
  "Rime's Bidding Ice",
  "Rime's Binding Dice",
  "Rime's Binding Lice",
  "Rime's Binding Mice",
  "Rime's Binding Nice",
  "Rime's Binding Rice",
  "Rime's Binding Vice",
  "Rime's Binding Ace",
  "Rime's Binding Ire",
  "Rime's Binding Ive",
  "Rime's Binding Icy",
  "Grope Trick",
  "Trope Trick",
  "Roe Trick",
  "Cope Trick",
  "Dope Trick",
  "Hope Trick",
  "Lope Trick",
  "Mope Trick",
  "Pope Trick",
  "Rape Trick",
  "Ripe Trick",
  "Robe Trick",
  "Rode Trick",
  "Role Trick",
  "Rome Trick",
  "Rose Trick",
  "Rote Trick",
  "Rove Trick",
  "Rope Tricky",
  "Rope Rick",
  "Rope Tick",
  "Rope Brick",
  "Rope Crick",
  "Rope Prick",
  "Rope Thick",
  "Rope Track",
  "Rope Truck",
  "Rope Trice",
  "Sacked Flame",
  "Scared Flame",
  "Sacred Aflame",
  "Sacred Lame",
  "Sacred Fame",
  "Sacred Blame",
  "Sacred Frame",
  "Sacred Flake",
  "Sacred Flare",
  "Slapping Sting",
  "Snapping Sting",
  "Swapping Sting",
  "Capping Sting",
  "Lapping Sting",
  "Mapping Sting",
  "Napping Sting",
  "Rapping Sting",
  "Tapping Sting",
  "Yapping Sting",
  "Zapping Sting",
  "Sipping Sting",
  "Sopping Sting",
  "Supping Sting",
  "Sapling Sting",
  "Sapping Sating",
  "Sapping Siting",
  "Sapping String",
  "Sapping Stingy",
  "Sapping Sing",
  "Sapping Sling",
  "Sapping Suing",
  "Sapping Swing",
  "Sapping Stung",
  "Sapping Stink",
  "Sapping Stint",
  "Shatter",
  "Spatter",
  "Scorching Bray",
  "Scorching Racy",
  "Scorching Dray",
  "Scorching Fray",
  "Scorching Pray",
  "Scorching Tray",
  "Scorching Xray",
  "Scorching Bay",
  "Scorching Day",
  "Scorching Gay",
  "Scorching Hay",
  "Scorching Jay",
  "Scorching Lay",
  "Scorching May",
  "Scorching Nay",
  "Scorching Pay",
  "Scorching Say",
  "Scorching Way",
  "Scorching Rad",
  "Scorching Rag",
  "Scorching Raj",
  "Scorching Ram",
  "Scorching Ran",
  "Scorching Rap",
  "Scorching Rat",
  "Scorching Raw",
  "Crying",
  "Shearing Smite",
  "Smearing Smite",
  "Spearing Smite",
  "Swearing Smite",
  "Bearing Smite",
  "Fearing Smite",
  "Gearing Smite",
  "Hearing Smite",
  "Nearing Smite",
  "Rearing Smite",
  "Tearing Smite",
  "Wearing Smite",
  "Scaring Smite",
  "Sharing Smite",
  "Snaring Smite",
  "Soaring Smite",
  "Sparing Smite",
  "Staring Smite",
  "Sealing Smite",
  "Seating Smite",
  "Searing Semite",
  "Searing Mite",
  "Searing Site",
  "Searing Spite",
  "Searing Suite",
  "Searing Smote",
  "Searing Smile",
  "Searing Smith",
  "Seek Invisibility",
  "Seem Invisibility",
  "Seen Invisibility",
  "Seep Invisibility",
  "Seer Invisibility",
  "Bee Invisibility",
  "Dee Invisibility",
  "Fee Invisibility",
  "Lee Invisibility",
  "Nee Invisibility",
  "Tee Invisibility",
  "Wee Invisibility",
  "She Invisibility",
  "Sue Invisibility",
  "Sea Invisibility",
  "Sec Invisibility",
  "Sen Invisibility",
  "Set Invisibility",
  "Sew Invisibility",
  "Sex Invisibility",
  "Seeing",
  "Deeming",
  "Teeming",
  "Seeding",
  "Seeking",
  "Seeping",
  "Spending",
  "Ending",
  "Bending",
  "Fending",
  "Lending",
  "Mending",
  "Pending",
  "Rending",
  "Tending",
  "Vending",
  "Wending",
  "Sanding",
  "Seeding",
  "Sensing",
  "Requester",
  "Shadowy Blade",
  "Shadow Lade",
  "Shadow Bade",
  "Shadow Glade",
  "Shadow Blame",
  "Shadow Blare",
  "Shadow Blase",
  "Shadow Blaze",
  "Shadowy of Moil",
  "Shadow Oaf Moil",
  "Shadow Off Moil",
  "Shadow Off Moil",
  "Shadow If Moil",
  "Shadow Oh Moil",
  "Shadow On Moil",
  "Shadow Or Moil",
  "Shadow Ow Moil",
  "Shadow Ox Moil",
  "Shadow of Oil",
  "Shadow of Boil",
  "Shadow of Coil",
  "Shadow of Foil",
  "Shadow of Soil",
  "Shadow of Toil",
  "Shadow of Mail",
  "Shaper Water",
  "Scape Water",
  "Shade Water",
  "Shake Water",
  "Shale Water",
  "Shame Water",
  "Share Water",
  "Shave Water",
  "Shape Waiter",
  "Shape Waster",
  "Shape Watery",
  "Shape Cater",
  "Shape Eater",
  "Shape Hater",
  "Shape Later",
  "Shape Mater",
  "Shape Pater",
  "Shape Rater",
  "Shape Wader",
  "Shape Wafer",
  "Shape Wager",
  "Shape Waver",
  "Hatter",
  "Chatter",
  "Scatter",
  "Spatter",
  "Shutter",
  "Shied",
  "Shied of Faith",
  "Shield Oaf Faith",
  "Shield Off Faith",
  "Shield Off Faith",
  "Shield If Faith",
  "Shield Oh Faith",
  "Shield On Faith",
  "Shield Or Faith",
  "Shield Ow Faith",
  "Shield Ox Faith",
  "Socking Grasp",
  "Stocking Grasp",
  "Shocking Rasp",
  "Shocking Gasp",
  "Shocking Grass",
  "Sickening Radiancy",
  "Silencer",
  "Silent Imago",
  "Kill Empowerment",
  "Spill Empowerment",
  "Still Empowerment",
  "Swill Empowerment",
  "Skull Empowerment",
  "Skirl Empowerment",
  "Asleep",
  "Sleepy",
  "Seep",
  "Bleep",
  "Sheep",
  "Steep",
  "Sweep",
  "Sleek",
  "Sleet",
  "Fleet Storm",
  "Sheet Storm",
  "Sweet Storm",
  "Slept Storm",
  "Sleek Storm",
  "Sleep Storm",
  "Sleet Stormy",
  "Sleet Store",
  "Sleet Stork",
  "Sleet Story",
  "Low",
  "Sow",
  "Blow",
  "Flow",
  "Glow",
  "Show",
  "Snow",
  "Stow",
  "Slew",
  "Slob",
  "Slog",
  "Slop",
  "Slot",
  "Scare",
  "Share",
  "Spare",
  "Stare",
  "Snore",
  "Snake",
  "Snarl",
  "Snilloc's Snowfall Swarm",
  "Snilloc's Snowball Warm",
  "Snilloc's Snowball Swam",
  "Snilloc's Snowball Sward",
  "Seoul Cage",
  "Foul Cage",
  "Soil Cage",
  "Souk Cage",
  "Soup Cage",
  "Sour Cage",
  "Soul Cadge",
  "Soul Cagey",
  "Soul Age",
  "Soul Gage",
  "Soul Page",
  "Soul Rage",
  "Soul Sage",
  "Soul Wage",
  "Soul Cade",
  "Soul Cafe",
  "Soul Cake",
  "Soul Came",
  "Soul Cane",
  "Soul Cape",
  "Soul Care",
  "Soul Case",
  "Soul Cave",
  "Soul Cagy",
  "Sparse the Dying",
  "Pare the Dying",
  "Spar the Dying",
  "Scare the Dying",
  "Share the Dying",
  "Snare the Dying",
  "Stare the Dying",
  "Spire the Dying",
  "Spore the Dying",
  "Space the Dying",
  "Spade the Dying",
  "Spate the Dying",
  "Spark the Dying",
  "Spars the Dying",
  "Spare Thee Dying",
  "Spare Thee Dying",
  "Spare Them Dying",
  "Spare Then Dying",
  "Spare They Dying",
  "Spare He Dying",
  "Spare She Dying",
  "Spare Tee Dying",
  "Spare Tie Dying",
  "Spare Toe Dying",
  "Spare Thy Dying",
  "Spare the Dyeing",
  "Spare the Drying",
  "Spare the Ding",
  "Spare the Lying",
  "Spare the Tying",
  "Spare the Vying",
  "Spare the Doing",
  "Peak with Animals",
  "Sneak with Animals",
  "Steak with Animals",
  "Speck with Animals",
  "Spear with Animals",
  "Speak Witch Animals",
  "Speak Width Animals",
  "Speak Wit Animals",
  "Speak Kith Animals",
  "Speak Pith Animals",
  "Speak Wish Animals",
  "Speak Wits Animals",
  "Peak with Dead",
  "Sneak with Dead",
  "Steak with Dead",
  "Speck with Dead",
  "Spear with Dead",
  "Speak Witch Dead",
  "Speak Width Dead",
  "Speak Wit Dead",
  "Speak Kith Dead",
  "Speak Pith Dead",
  "Speak Wish Dead",
  "Speak Wits Dead",
  "Speak with Dread",
  "Speak with Dad",
  "Speak with Bead",
  "Speak with Head",
  "Speak with Lead",
  "Speak with Mead",
  "Speak with Read",
  "Speak with Dyad",
  "Speak with Deed",
  "Speak with Deaf",
  "Speak with Deal",
  "Speak with Dean",
  "Speak with Dear",
  "Peak with Plants",
  "Sneak with Plants",
  "Steak with Plants",
  "Speck with Plants",
  "Spear with Plants",
  "Speak Witch Plants",
  "Speak Width Plants",
  "Speak Wit Plants",
  "Speak Kith Plants",
  "Speak Pith Plants",
  "Speak Wish Plants",
  "Speak Wits Plants",
  "Speak with Planets",
  "Speak with Pants",
  "Speak with Plans",
  "Speak with Slants",
  "Speak with Plaits",
  "Speak with Planes",
  "Speak with Planks",
  "Spidery Climb",
  "Sider Climb",
  "Slider Climb",
  "Spicer Climb",
  "Spider Limb",
  "Pike Growth",
  "Spoke Growth",
  "Spice Growth",
  "Spine Growth",
  "Spire Growth",
  "Spite Growth",
  "Spiky Growth",
  "Swaggering Smite",
  "Staggering Semite",
  "Staggering Mite",
  "Staggering Site",
  "Staggering Spite",
  "Staggering Suite",
  "Staggering Smote",
  "Staggering Smile",
  "Staggering Smith",
  "Steely Wind Strike",
  "Steal Wind Strike",
  "Steed Wind Strike",
  "Steep Wind Strike",
  "Steer Wind Strike",
  "Steel Wined Strike",
  "Steel Windy Strike",
  "Steel Win Strike",
  "Steel Bind Strike",
  "Steel Find Strike",
  "Steel Hind Strike",
  "Steel Kind Strike",
  "Steel Mind Strike",
  "Steel Rind Strike",
  "Steel Wand Strike",
  "Steel Wend Strike",
  "Steel Wild Strike",
  "Steel Wine Strike",
  "Steel Wing Strike",
  "Steel Wink Strike",
  "Steel Wins Strike",
  "Steel Wind Striker",
  "Steel Wind Stroke",
  "Steel Wind Stride",
  "Steel Wind Strife",
  "Steel Wind Stripe",
  "Steel Wind Strive",
  "Sinking Cloud",
  "Slinking Cloud",
  "Sticking Cloud",
  "Stinging Cloud",
  "Stinking Cloudy",
  "Stinking Loud",
  "Stinking Clod",
  "Stinking Aloud",
  "Stinking Clout",
  "Tone Shape",
  "Atone Shape",
  "Scone Shape",
  "Shone Shape",
  "Stoke Shape",
  "Stole Shape",
  "Store Shape",
  "Stove Shape",
  "Stony Shape",
  "Stone Shaper",
  "Stone Scape",
  "Stone Shade",
  "Stone Shake",
  "Stone Shale",
  "Stone Shame",
  "Stone Share",
  "Stone Shave",
  "Stormy of Vengeance",
  "Store of Vengeance",
  "Stork of Vengeance",
  "Story of Vengeance",
  "Storm Oaf Vengeance",
  "Storm Off Vengeance",
  "Storm Off Vengeance",
  "Storm If Vengeance",
  "Storm Oh Vengeance",
  "Storm On Vengeance",
  "Storm Or Vengeance",
  "Storm Ow Vengeance",
  "Storm Ox Vengeance",
  "Stormy Sphere",
  "Store Sphere",
  "Stork Sphere",
  "Story Sphere",
  "Summon Breast",
  "Summon East",
  "Summon Best",
  "Summon Beat",
  "Summon Feast",
  "Summon Least",
  "Summon Yeast",
  "Summon Blast",
  "Summon Boast",
  "Summon Beats",
  "Summon Constrict",
  "Summon Hey",
  "Summon Key",
  "Summon Fly",
  "Summon Fry",
  "Summon Fed",
  "Summon Fee",
  "Summon Fen",
  "Summon Few",
  "Summon Fez",
  "Summon Friend",
  "Summon Fend",
  "Summon Find",
  "Summon Field",
  "Summon Fined",
  "Summon Grater Demon",
  "Summon Greater Daemon",
  "Summon Greater Demo",
  "Summon Greater Lemon",
  "Summon Lessor Demons",
  "Summon Lessee Demons",
  "Summon Lessen Demons",
  "Summon Lesser Daemons",
  "Summon Lesser Lemons",
  "Summon Lesser Demobs",
  "Summon Unread",
  "Sunburnt",
  "Sift Quiver",
  "Shift Quiver",
  "Swift Quaver",
  "Word Burst",
  "Sward Burst",
  "Swore Burst",
  "Sworn Burst",
  "Sword Bust",
  "Sword Burs",
  "Sword Burnt",
  "Synoptic Static",
  "Tasha's Caustic Crew",
  "Tasha's Caustic Drew",
  "Tasha's Caustic Grew",
  "Tasha's Caustic Blew",
  "Tasha's Caustic Braw",
  "Tasha's Caustic Brow",
  "Tasha's Caustic Bred",
  "Tasha's Hideouts Laughter",
  "Tasha's Hideout Laughter",
  "Tasha's Hideous Slaughter",
  "Tasha's Hideous Laugher",
  "Tasha's Hideous Daughter",
  "Tasha's Mined Whip",
  "Tasha's Mid Whip",
  "Tasha's Bind Whip",
  "Tasha's Find Whip",
  "Tasha's Hind Whip",
  "Tasha's Kind Whip",
  "Tasha's Rind Whip",
  "Tasha's Wind Whip",
  "Tasha's Mend Whip",
  "Tasha's Mild Whip",
  "Tasha's Mine Whip",
  "Tasha's Mini Whip",
  "Tasha's Mink Whip",
  "Tasha's Mint Whip",
  "Tasha's Minx Whip",
  "Tasha's Mind Hip",
  "Tasha's Mind Chip",
  "Tasha's Mind Ship",
  "Tasha's Mind Whap",
  "Tasha's Mind Whop",
  "Tasha's Mind Whim",
  "Tasha's Mind Whir",
  "Tasha's Otherworldly Guide",
  "Tasha's Otherworldly Guile",
  "Teleportation Circlet",
  "Temple Oaf the Gods",
  "Temple Off the Gods",
  "Temple Off the Gods",
  "Temple If the Gods",
  "Temple Oh the Gods",
  "Temple On the Gods",
  "Temple Or the Gods",
  "Temple Ow the Gods",
  "Temple Ox the Gods",
  "Temple of Thee Gods",
  "Temple of Thee Gods",
  "Temple of Them Gods",
  "Temple of Then Gods",
  "Temple of They Gods",
  "Temple of He Gods",
  "Temple of She Gods",
  "Temple of Tee Gods",
  "Temple of Tie Gods",
  "Temple of Toe Gods",
  "Temple of Thy Gods",
  "Temple of the Goads",
  "Temple of the Golds",
  "Temple of the Goods",
  "Temple of the Goods",
  "Temple of the Cods",
  "Temple of the Nods",
  "Temple of the Pods",
  "Temple of the Rods",
  "Temple of the Sods",
  "Temple of the Goes",
  "Temporal Hunt",
  "Temporal Shut",
  "Temporal Shun",
  "Temporal Stunt",
  "Temporal Shuns",
  "Tenser's Bloating Disk",
  "Tenser's Gloating Disk",
  "Tenser's Flouting Disk",
  "Tenser's Floating Risk",
  "Tenser's Floating Desk",
  "Tenser's Floating Dusk",
  "Tenser's Floating Dick",
  "Tenser's Floating Disc",
  "Tenser's Floating Dish",
  "Ether Essence",
  "Nether Essence",
  "Wether Essence",
  "Thaumaturge",
  "Thorny Whip",
  "Horn Whip",
  "Torn Whip",
  "Thor Whip",
  "Shorn Whip",
  "Thorn Hip",
  "Thorn Chip",
  "Thorn Ship",
  "Thorn Whap",
  "Thorn Whop",
  "Thorn Whim",
  "Thorn Whir",
  "Thundery Step",
  "Thunder Steep",
  "Thunder Steep",
  "Thunder Stoep",
  "Thunder Seep",
  "Thunder Stop",
  "Thunder Stem",
  "Thunder Stet",
  "Thunder Stew",
  "Thunderous Semite",
  "Thunderous Mite",
  "Thunderous Site",
  "Thunderous Spite",
  "Thunderous Suite",
  "Thunderous Smote",
  "Thunderous Smile",
  "Thunderous Smith",
  "Tidal Weave",
  "Tidal Waive",
  "Tidal Waver",
  "Tidal Ave",
  "Tidal Cave",
  "Tidal Gave",
  "Tidal Have",
  "Tidal Nave",
  "Tidal Pave",
  "Tidal Rave",
  "Tidal Save",
  "Tidal Wove",
  "Tidal Wade",
  "Tidal Wage",
  "Tidal Wake",
  "Tidal Wane",
  "Tidal Ware",
  "Tidal Wavy",
  "Timer Ravage",
  "Tie Ravage",
  "Dime Ravage",
  "Lime Ravage",
  "Mime Ravage",
  "Rime Ravage",
  "Tame Ravage",
  "Tome Ravage",
  "Tide Ravage",
  "Tile Ravage",
  "Tire Ravage",
  "Time Savage",
  "Timer Stop",
  "Tie Stop",
  "Dime Stop",
  "Lime Stop",
  "Mime Stop",
  "Rime Stop",
  "Tame Stop",
  "Tome Stop",
  "Tide Stop",
  "Tile Stop",
  "Tire Stop",
  "Time Stoep",
  "Time Stomp",
  "Time Stoop",
  "Time Stoop",
  "Time Strop",
  "Time Top",
  "Time Sop",
  "Time Atop",
  "Time Shop",
  "Time Slop",
  "Time Swop",
  "Time Step",
  "Time Stoa",
  "Time Stow",
  "Tinny Servant",
  "Tinny Servant",
  "Tin Servant",
  "Liny Servant",
  "Piny Servant",
  "Tony Servant",
  "Tidy Servant",
  "Tins Servant",
  "Tint Servant",
  "Atoll the Dead",
  "Troll the Dead",
  "Doll the Dead",
  "Loll the Dead",
  "Poll the Dead",
  "Roll the Dead",
  "Tall the Dead",
  "Tell the Dead",
  "Till the Dead",
  "Toil the Dead",
  "Tool the Dead",
  "Told the Dead",
  "Toll Thee Dead",
  "Toll Thee Dead",
  "Toll Them Dead",
  "Toll Then Dead",
  "Toll They Dead",
  "Toll He Dead",
  "Toll She Dead",
  "Toll Tee Dead",
  "Toll Tie Dead",
  "Toll Toe Dead",
  "Toll Thy Dead",
  "Toll the Dread",
  "Toll the Dad",
  "Toll the Bead",
  "Toll the Head",
  "Toll the Lead",
  "Toll the Mead",
  "Toll the Read",
  "Toll the Dyad",
  "Toll the Deed",
  "Toll the Deaf",
  "Toll the Deal",
  "Toll the Dean",
  "Toll the Dear",
  "Transmute Crock",
  "Transmute Frock",
  "Transmute Rocky",
  "Transmute Roc",
  "Transmute Cock",
  "Transmute Dock",
  "Transmute Hock",
  "Transmute Jock",
  "Transmute Lock",
  "Transmute Mock",
  "Transmute Pock",
  "Transmute Sock",
  "Transmute Rack",
  "Transmute Rick",
  "Transmute Ruck",
  "Transmute Rook",
  "Transmute Rocs",
  "Transport Vial Plants",
  "Transport Visa Plants",
  "Transport Viva Plants",
  "Transport Ria Plants",
  "Transport Vie Plants",
  "Transport Vim Plants",
  "Transport via Planets",
  "Transport via Pants",
  "Transport via Plans",
  "Transport via Slants",
  "Transport via Plaits",
  "Transport via Planes",
  "Transport via Planks",
  "Three Stride",
  "Tee Stride",
  "Free Stride",
  "Thee Stride",
  "Twee Stride",
  "True Stride",
  "Trek Stride",
  "Tree Astride",
  "Tree Strider",
  "Tree Strode",
  "Tree Strife",
  "Tree Strike",
  "Tree Stripe",
  "Tree Strive",
  "Truce Polymorph",
  "Truer Polymorph",
  "Rue Polymorph",
  "Tree Polymorph",
  "Truce Resurrection",
  "Truer Resurrection",
  "Rue Resurrection",
  "Tree Resurrection",
  "Truce Seeing",
  "Truer Seeing",
  "Rue Seeing",
  "Tree Seeing",
  "True Seeding",
  "True Seeking",
  "True Seeming",
  "True Seeping",
  "True Teeing",
  "True Sewing",
  "True Sexing",
  "Truce Strike",
  "Truer Strike",
  "Rue Strike",
  "Tree Strike",
  "True Striker",
  "True Stroke",
  "True Stride",
  "True Strife",
  "True Stripe",
  "True Strive",
  "Vampiric Touche",
  "Vampiric Touchy",
  "Vampiric Ouch",
  "Vampiric Couch",
  "Vampiric Pouch",
  "Vampiric Vouch",
  "Vampiric Torch",
  "Vampiric Tough",
  "Vicious Mocker",
  "Vicious Rockery",
  "Vicious Mockers",
  "All of Fire",
  "Ball of Fire",
  "Call of Fire",
  "Fall of Fire",
  "Gall of Fire",
  "Hall of Fire",
  "Mall of Fire",
  "Pall of Fire",
  "Tall of Fire",
  "Well of Fire",
  "Will of Fire",
  "Wail of Fire",
  "Walk of Fire",
  "Wall Oaf Fire",
  "Wall Off Fire",
  "Wall Off Fire",
  "Wall If Fire",
  "Wall Oh Fire",
  "Wall On Fire",
  "Wall Or Fire",
  "Wall Ow Fire",
  "Wall Ox Fire",
  "Wall of Afire",
  "Wall of Fibre",
  "Wall of Firer",
  "Wall of Ire",
  "Wall of Fir",
  "Wall of Aire",
  "Wall of Dire",
  "Wall of Eire",
  "Wall of Hire",
  "Wall of Lire",
  "Wall of Mire",
  "Wall of Sire",
  "Wall of Tire",
  "Wall of Wire",
  "Wall of Fare",
  "Wall of Fore",
  "Wall of Fife",
  "Wall of File",
  "Wall of Fine",
  "Wall of Five",
  "Wall of Firm",
  "Wall of Firs",
  "All of Force",
  "Ball of Force",
  "Call of Force",
  "Fall of Force",
  "Gall of Force",
  "Hall of Force",
  "Mall of Force",
  "Pall of Force",
  "Tall of Force",
  "Well of Force",
  "Will of Force",
  "Wail of Force",
  "Walk of Force",
  "Wall Oaf Force",
  "Wall Off Force",
  "Wall Off Force",
  "Wall If Force",
  "Wall Oh Force",
  "Wall On Force",
  "Wall Or Force",
  "Wall Ow Force",
  "Wall Ox Force",
  "Wall of Fore",
  "Wall of Farce",
  "Wall of Forge",
  "Wall of Forte",
  "All of Ice",
  "Ball of Ice",
  "Call of Ice",
  "Fall of Ice",
  "Gall of Ice",
  "Hall of Ice",
  "Mall of Ice",
  "Pall of Ice",
  "Tall of Ice",
  "Well of Ice",
  "Will of Ice",
  "Wail of Ice",
  "Walk of Ice",
  "Wall Oaf Ice",
  "Wall Off Ice",
  "Wall Off Ice",
  "Wall If Ice",
  "Wall Oh Ice",
  "Wall On Ice",
  "Wall Or Ice",
  "Wall Ow Ice",
  "Wall Ox Ice",
  "Wall of Dice",
  "Wall of Lice",
  "Wall of Mice",
  "Wall of Nice",
  "Wall of Rice",
  "Wall of Vice",
  "Wall of Ace",
  "Wall of Ire",
  "Wall of Ive",
  "Wall of Icy",
  "All of Light",
  "Ball of Light",
  "Call of Light",
  "Fall of Light",
  "Gall of Light",
  "Hall of Light",
  "Mall of Light",
  "Pall of Light",
  "Tall of Light",
  "Well of Light",
  "Will of Light",
  "Wail of Light",
  "Walk of Light",
  "Wall Oaf Light",
  "Wall Off Light",
  "Wall Off Light",
  "Wall If Light",
  "Wall Oh Light",
  "Wall On Light",
  "Wall Or Light",
  "Wall Ow Light",
  "Wall Ox Light",
  "Wall of Alight",
  "Wall of Blight",
  "Wall of Flight",
  "Wall of Plight",
  "Wall of Slight",
  "Wall of Eight",
  "Wall of Fight",
  "Wall of Hight",
  "Wall of Might",
  "Wall of Night",
  "Wall of Right",
  "Wall of Sight",
  "Wall of Tight",
  "All of Sand",
  "Ball of Sand",
  "Call of Sand",
  "Fall of Sand",
  "Gall of Sand",
  "Hall of Sand",
  "Mall of Sand",
  "Pall of Sand",
  "Tall of Sand",
  "Well of Sand",
  "Will of Sand",
  "Wail of Sand",
  "Walk of Sand",
  "Wall Oaf Sand",
  "Wall Off Sand",
  "Wall Off Sand",
  "Wall If Sand",
  "Wall Oh Sand",
  "Wall On Sand",
  "Wall Or Sand",
  "Wall Ow Sand",
  "Wall Ox Sand",
  "Wall of Stand",
  "Wall of Sandy",
  "Wall of And",
  "Wall of Sad",
  "Wall of San",
  "Wall of Band",
  "Wall of Hand",
  "Wall of Land",
  "Wall of Rand",
  "Wall of Wand",
  "Wall of Send",
  "Wall of Said",
  "Wall of Sane",
  "Wall of Sang",
  "Wall of Sank",
  "All of Stone",
  "Ball of Stone",
  "Call of Stone",
  "Fall of Stone",
  "Gall of Stone",
  "Hall of Stone",
  "Mall of Stone",
  "Pall of Stone",
  "Tall of Stone",
  "Well of Stone",
  "Will of Stone",
  "Wail of Stone",
  "Walk of Stone",
  "Wall Oaf Stone",
  "Wall Off Stone",
  "Wall Off Stone",
  "Wall If Stone",
  "Wall Oh Stone",
  "Wall On Stone",
  "Wall Or Stone",
  "Wall Ow Stone",
  "Wall Ox Stone",
  "Wall of Tone",
  "Wall of Atone",
  "Wall of Scone",
  "Wall of Shone",
  "Wall of Stoke",
  "Wall of Stole",
  "Wall of Store",
  "Wall of Stove",
  "Wall of Stony",
  "All of Thorns",
  "Ball of Thorns",
  "Call of Thorns",
  "Fall of Thorns",
  "Gall of Thorns",
  "Hall of Thorns",
  "Mall of Thorns",
  "Pall of Thorns",
  "Tall of Thorns",
  "Well of Thorns",
  "Will of Thorns",
  "Wail of Thorns",
  "Walk of Thorns",
  "Wall Oaf Thorns",
  "Wall Off Thorns",
  "Wall Off Thorns",
  "Wall If Thorns",
  "Wall Oh Thorns",
  "Wall On Thorns",
  "Wall Or Thorns",
  "Wall Ow Thorns",
  "Wall Ox Thorns",
  "Wall of Horns",
  "Wall of Thorny",
  "All of Water",
  "Ball of Water",
  "Call of Water",
  "Fall of Water",
  "Gall of Water",
  "Hall of Water",
  "Mall of Water",
  "Pall of Water",
  "Tall of Water",
  "Well of Water",
  "Will of Water",
  "Wail of Water",
  "Walk of Water",
  "Wall Oaf Water",
  "Wall Off Water",
  "Wall Off Water",
  "Wall If Water",
  "Wall Oh Water",
  "Wall On Water",
  "Wall Or Water",
  "Wall Ow Water",
  "Wall Ox Water",
  "Wall of Waiter",
  "Wall of Waster",
  "Wall of Watery",
  "Wall of Cater",
  "Wall of Eater",
  "Wall of Hater",
  "Wall of Later",
  "Wall of Mater",
  "Wall of Pater",
  "Wall of Rater",
  "Wall of Wader",
  "Wall of Wafer",
  "Wall of Wager",
  "Wall of Waver",
  "Awarding Bond",
  "Wading Bond",
  "Waring Bond",
  "Carding Bond",
  "Wording Bond",
  "Wadding Bond",
  "Warming Bond",
  "Warning Bond",
  "Warping Bond",
  "Warring Bond",
  "Warding Boned",
  "Warding Blond",
  "Warding Bound",
  "Warding Fond",
  "Warding Pond",
  "Warding Band",
  "Warding Bend",
  "Warding Bind",
  "Warding Bold",
  "Warding Bone",
  "Warding Bong",
  "Warding Bonn",
  "Warding Bony",
  "Awarding Wind",
  "Wading Wind",
  "Waring Wind",
  "Carding Wind",
  "Wording Wind",
  "Wadding Wind",
  "Warming Wind",
  "Warning Wind",
  "Warping Wind",
  "Warring Wind",
  "Warding Wined",
  "Warding Windy",
  "Warding Win",
  "Warding Bind",
  "Warding Find",
  "Warding Hind",
  "Warding Kind",
  "Warding Mind",
  "Warding Rind",
  "Warding Wand",
  "Warding Wend",
  "Warding Wild",
  "Warding Wine",
  "Warding Wing",
  "Warding Wink",
  "Warding Wins",
  "Waiter Breathing",
  "Waster Breathing",
  "Watery Breathing",
  "Cater Breathing",
  "Eater Breathing",
  "Hater Breathing",
  "Later Breathing",
  "Mater Breathing",
  "Pater Breathing",
  "Rater Breathing",
  "Wader Breathing",
  "Wafer Breathing",
  "Wager Breathing",
  "Waver Breathing",
  "Water Wreathing",
  "Water Breaching",
  "Waiter Walk",
  "Waster Walk",
  "Watery Walk",
  "Cater Walk",
  "Eater Walk",
  "Hater Walk",
  "Later Walk",
  "Mater Walk",
  "Pater Walk",
  "Rater Walk",
  "Wader Walk",
  "Wafer Walk",
  "Wager Walk",
  "Waver Walk",
  "Water Talk",
  "Water Wall",
  "Water Sphere",
  "Eatery Sphere",
  "Waters Sphere",
  "We",
  "Deb",
  "Wed",
  "Wee",
  "Wet",
  "Weirdo",
  "Weir",
  "Weirs",
  "Wined Walk",
  "Windy Walk",
  "Win Walk",
  "Bind Walk",
  "Find Walk",
  "Hind Walk",
  "Kind Walk",
  "Mind Walk",
  "Rind Walk",
  "Wand Walk",
  "Wend Walk",
  "Wild Walk",
  "Wine Walk",
  "Wing Walk",
  "Wink Walk",
  "Wins Walk",
  "Wind Talk",
  "Wind Wall",
  "Wined Wall",
  "Windy Wall",
  "Win Wall",
  "Bind Wall",
  "Find Wall",
  "Hind Wall",
  "Kind Wall",
  "Mind Wall",
  "Rind Wall",
  "Wand Wall",
  "Wend Wall",
  "Wild Wall",
  "Wine Wall",
  "Wing Wall",
  "Wink Wall",
  "Wins Wall",
  "Wind All",
  "Wind Ball",
  "Wind Call",
  "Wind Fall",
  "Wind Gall",
  "Wind Hall",
  "Wind Mall",
  "Wind Pall",
  "Wind Tall",
  "Wind Well",
  "Wind Will",
  "Wind Wail",
  "Wind Walk",
  "Swish",
  "Dish",
  "Fish",
  "Wash",
  "With",
  "Wise",
  "Wisp",
  "Switch Bolt",
  "Twitch Bolt",
  "Itch Bolt",
  "With Bolt",
  "Bitch Bolt",
  "Ditch Bolt",
  "Hitch Bolt",
  "Pitch Bolt",
  "Watch Bolt",
  "Winch Bolt",
  "Witch Colt",
  "Witch Dolt",
  "Witch Jolt",
  "Witch Volt",
  "Witch Belt",
  "Witch Boat",
  "Witch Boot",
  "Witch Bout",
  "Witch Bola",
  "Witch Bold",
  "Witch Bole",
  "Witch Blot",
  "World of Radiance",
  "Sword of Radiance",
  "Wordy of Radiance",
  "Cord of Radiance",
  "Ford of Radiance",
  "Lord of Radiance",
  "Ward of Radiance",
  "Woad of Radiance",
  "Wold of Radiance",
  "Wood of Radiance",
  "Wore of Radiance",
  "Work of Radiance",
  "Worm of Radiance",
  "Worn of Radiance",
  "Word Oaf Radiance",
  "Word Off Radiance",
  "Word Off Radiance",
  "Word If Radiance",
  "Word Oh Radiance",
  "Word On Radiance",
  "Word Or Radiance",
  "Word Ow Radiance",
  "Word Ox Radiance",
  "Word of Radiancy",
  "World of Recall",
  "Sword of Recall",
  "Wordy of Recall",
  "Cord of Recall",
  "Ford of Recall",
  "Lord of Recall",
  "Ward of Recall",
  "Woad of Recall",
  "Wold of Recall",
  "Wood of Recall",
  "Wore of Recall",
  "Work of Recall",
  "Worm of Recall",
  "Worn of Recall",
  "Word Oaf Recall",
  "Word Off Recall",
  "Word Off Recall",
  "Word If Recall",
  "Word Oh Recall",
  "Word On Recall",
  "Word Or Recall",
  "Word Ow Recall",
  "Word Ox Recall",
  "Wreath of Nature",
  "Wraith of Nature",
  "Wrath Oaf Nature",
  "Wrath Off Nature",
  "Wrath Off Nature",
  "Wrath If Nature",
  "Wrath Oh Nature",
  "Wrath On Nature",
  "Wrath Or Nature",
  "Wrath Ow Nature",
  "Wrath Ox Nature",
  "Wrath of Mature",
  "Wrathful Semite",
  "Wrathful Mite",
  "Wrathful Site",
  "Wrathful Spite",
  "Wrathful Suite",
  "Wrathful Smote",
  "Wrathful Smile",
  "Wrathful Smith",
  "Zephyr Striker",
  "Zephyr Stroke",
  "Zephyr Stride",
  "Zephyr Strife",
  "Zephyr Stripe",
  "Zephyr Strive",
  "Ozone of Truth",
  "One of Truth",
  "Bone of Truth",
  "Cone of Truth",
  "Done of Truth",
  "Gone of Truth",
  "Hone of Truth",
  "Lone of Truth",
  "None of Truth",
  "Tone of Truth",
  "Zone Oaf Truth",
  "Zone Off Truth",
  "Zone Off Truth",
  "Zone If Truth",
  "Zone Oh Truth",
  "Zone On Truth",
  "Zone Or Truth",
  "Zone Ow Truth",
  "Zone Ox Truth",
  "Zone of Ruth",
]